name: linuxserver-freetube
services:
  freetube:
    image: linuxserver/freetube:version-190523148@sha256:ee7d62df4e863097a0f9e5041e09542f1b8fb33421f479327814825c21de0926
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freetube/config
        target: /config
x-casaos:
  main: freetube
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.freetube/assets/icon.png
  title:
    en_US: Freetube
  id: by-roket.linuxserver.freetube
  version: version-190523148
  index: /
  port_map: '3000'
