name: linuxserver-winegui
services:
  winegui:
    image: linuxserver/winegui:4.3.2@sha256:0b45a28b9bf8e889623923d89e80acc8aa546861965848842d54d301b4cecd4a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: winegui-by-roket
x-casaos:
  main: winegui
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.winegui/assets/icon.png
  title:
    en_US: Winegui (LinuxServer.io)
  id: by-roket.linuxserver.winegui
  port_map: '3000'
  version: 4.3.2
  index: /
