name: linuxserver-webgrabplus
services:
  webgrabplus:
    image: linuxserver/webgrabplus:5.6.0@sha256:a2f33a4c9c4fbaf46666f0537fcb23a2a2b784765240dc77ccb37fd973e98329
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: webgrabplus-by-roket
x-casaos:
  main: webgrabplus
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.webgrabplus/assets/icon.jpg
  title:
    en_US: Webgrabplus
  port_map: '80'
  id: by-roket.linuxserver.webgrabplus
  version: 5.6.0
  index: /
