name: linuxserver-webgrabplus
services:
  webgrabplus:
    image: linuxserver/webgrabplus:5.6.1@sha256:521050fdcf7f59d2922e5200aa0bfc85ad172128c0969463d36916c16b4b256c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: webgrabplus-by-roket
x-casaos:
  main: webgrabplus
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.webgrabplus/assets/icon.jpg
  title:
    en_US: Webgrabplus (LinuxServer.io)
  id: by-roket.linuxserver.webgrabplus
  port_map: '80'
  version: 5.6.1
  index: /
