name: linuxserver-beets
services:
  beets:
    image: linuxserver/beets:2.13.1@sha256:36d94a2c33d6534b7016f1294dc3350393318451ec9a867d6b3c48c5c948c642
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8337
        published: 8337
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/beets/config
        target: /config
      - type: bind
        source: /DATA/AppData/beets/music
        target: /music
      - type: bind
        source: /DATA/AppData/beets/downloads
        target: /downloads
x-casaos:
  main: beets
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.beets/assets/icon.png
  title:
    en_US: Beets
  port_map: '8337'
  id: by-roket.linuxserver.beets
  version: 2.13.1
  index: /
