name: linuxserver-beets
services:
  beets:
    image: linuxserver/beets:2.13.1@sha256:a2487fe89dae71e33108d2e6ef8fbbd1eff35cf73972e25abf6a4d92cf23f432
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8337
        published: 8337
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/music
        target: /music
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: beets-by-roket
x-casaos:
  main: beets
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.beets/assets/icon.png
  title:
    en_US: Beets (LinuxServer.io)
  id: by-roket.linuxserver.beets
  port_map: '8337'
  version: 2.13.1
  index: /
