name: linuxserver-duckdns
services:
  duckdns:
    image: linuxserver/duckdns:version-af6dcae5@sha256:ecb7fb57396c33f5c8dfb3b4017324922bf02b046b4e5b455ca975c2801d8170
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SUBDOMAINS: ''
      TOKEN: ''
      UPDATE_IP: ''
      LOG_FILE: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: duckdns-by-roket
x-casaos:
  main: duckdns
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.duckdns/assets/icon.png
  title:
    en_US: Duckdns
  port_map: '80'
  id: by-roket.linuxserver.duckdns
  version: version-af6dcae5
  index: /
