name: linuxserver-duckdns
services:
  duckdns:
    image: linuxserver/duckdns:version-6be4c9e7@sha256:4f1cc4d1cd1b8ff1cc7b4d4d178e3a9e05160ce68e3d6a02c5e16038f2fe83c6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SUBDOMAINS: ''
      TOKEN: ''
      UPDATE_IP: ''
      LOG_FILE: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: duckdns-by-roket
x-casaos:
  main: duckdns
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.duckdns/assets/icon.png
  title:
    en_US: Duckdns (LinuxServer.io)
  id: by-roket.linuxserver.duckdns
  port_map: '80'
  version: version-6be4c9e7
  index: /
