name: linuxserver-syslog-ng
services:
  syslog-ng:
    image: linuxserver/syslog-ng:4.11.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LOG_TO_STDOUT: ''
    ports:
      - target: 514
        published: 5514
        protocol: udp
      - target: 601
        published: 6601
        protocol: tcp
      - target: 6514
        published: 6514
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/syslog-ng/config
        target: /config
      - type: bind
        source: /var/log
        target: /var/log
x-casaos:
  main: syslog-ng
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.syslog-ng/assets/icon.png
  title:
    en_US: Syslog ng
  id: by-roket.linuxserver.syslog-ng
  version: 4.11.0
  index: /
  port_map: ''
