name: linuxserver-brave
services:
  brave:
    image: linuxserver/brave:1.93.138@sha256:e3be86eeaf2495632a7efebd26112f121020285f91ba30f45d18a76d16726ebb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/brave/config
        target: /config
x-casaos:
  main: brave
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.brave/assets/icon.png
  title:
    en_US: Brave
  port_map: '3000'
  id: by-roket.linuxserver.brave
  version: 1.93.138
  index: /
