name: linuxserver-brave
services:
  brave:
    image: linuxserver/brave:1.94.117@sha256:1639bb0452c2ba5b59c24adf423eb86a49234f5d3ed5837b4b4be5ee83f7c9df
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: brave-by-roket
x-casaos:
  main: brave
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.brave/assets/icon.png
  title:
    en_US: Brave
  port_map: '3000'
  id: by-roket.linuxserver.brave
  version: 1.94.117
  index: /
