name: linuxserver-brave
services:
  brave:
    image: linuxserver/brave:1.94.117@sha256:91d8c489f99d1d77db97c17cdc01cd9049ede93013b762a1476331b6696124b3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: brave-by-roket
x-casaos:
  main: brave
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.brave/assets/icon.png
  title:
    en_US: Brave (LinuxServer.io)
  id: by-roket.linuxserver.brave
  port_map: '3000'
  version: 1.94.117
  index: /
