name: linuxserver-brave
services:
  brave:
    image: linuxserver/brave:1.94.119@sha256:fe6f636574c09c66d9eeaf133d5763d76754b73db47d977d1a4465a9b7f173d9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: brave-by-roket
x-casaos:
  main: brave
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.brave/assets/icon.png
  title:
    en_US: Brave (LinuxServer.io)
  id: by-roket.linuxserver.brave
  port_map: '3000'
  version: 1.94.119
  index: /
