name: linuxserver-vlc
services:
  vlc:
    image: linuxserver/vlc:3.0.23
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VLC_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: vlc-by-roket
x-casaos:
  main: vlc
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.vlc/assets/icon.png
  title:
    en_US: Vlc (LinuxServer.io)
  id: by-roket.linuxserver.vlc
  port_map: '3000'
  version: 3.0.23
  index: /
