name: linuxserver-modrinth
services:
  modrinth:
    image: linuxserver/modrinth:0.19.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: modrinth-by-roket
x-casaos:
  main: modrinth
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.modrinth/assets/icon.png
  title:
    en_US: Modrinth (LinuxServer.io)
  id: by-roket.linuxserver.modrinth
  port_map: '3000'
  version: 0.19.2
  index: /
