name: linuxserver-msedge
services:
  msedge:
    image: linuxserver/msedge:151.0.4129@sha256:c92be8dd14e572a61b58109bb666ccd2e50376d00434d99ff1fde14a686e0234
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EDGE_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/msedge/config
        target: /config
x-casaos:
  main: msedge
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.msedge/assets/icon.png
  title:
    en_US: Msedge
  port_map: '3000'
  id: by-roket.linuxserver.msedge
  version: 151.0.4129
  index: /
