name: linuxserver-ombi
services:
  ombi:
    image: linuxserver/ombi:4.53.10@sha256:5309425c906bbbb4837d19a8b59bcbc08941100aaaf8c0b6b565c6325d118c0e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
    ports:
      - target: 3579
        published: 3579
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: ombi-by-roket
x-casaos:
  main: ombi
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ombi/assets/icon.png
  title:
    en_US: Ombi
  port_map: '3579'
  id: by-roket.linuxserver.ombi
  version: 4.53.10
  index: /
