name: linuxserver-ombi
services:
  app:
    image: linuxserver/ombi:4.53.10@sha256:c3adbcadede99886c1620ebecd0452988c36fc30a6e557a4c7b40f6c97b8fcf2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
    ports:
      - target: 3579
        published: 3579
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ombi/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ombi/assets/icon.png
  title:
    en_US: Ombi
  port_map: '3579'
  id: by-roket.linuxserver.ombi
  version: 4.53.10
  index: /
