name: linuxserver-zotero
services:
  zotero:
    image: linuxserver/zotero:10.0.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: zotero-by-roket
x-casaos:
  main: zotero
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.zotero/assets/icon.png
  title:
    en_US: Zotero (LinuxServer.io)
  id: by-roket.linuxserver.zotero
  port_map: '3000'
  version: 10.0.1
  index: /
