name: linuxserver-chromium
services:
  chromium:
    image: linuxserver/chromium:arm64v8-version-fc3ad042@sha256:5cce93f7680c5c3d32f946d0f0d2c53e3f02a8e982e2ca8516367423951eca48
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: chromium-by-roket
x-casaos:
  main: chromium
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.chromium/assets/icon.png
  title:
    en_US: Chromium (LinuxServer.io)
  id: by-roket.linuxserver.chromium
  port_map: '3000'
  version: arm64v8-version-fc3ad042
  index: /
