name: linuxserver-chromium
services:
  chromium:
    image: linuxserver/chromium:version-be140933@sha256:c1f4607cc2a6bfb74a1142ea288a3d9465071d5a6e20043126de3029875578d5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: chromium-by-roket
x-casaos:
  main: chromium
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.chromium/assets/icon.png
  title:
    en_US: Chromium
  port_map: '3000'
  id: by-roket.linuxserver.chromium
  version: version-be140933
  index: /
