name: linuxserver-chromium
services:
  chromium:
    image: linuxserver/chromium:arm64v8-version-d39975b5@sha256:e6d91233acf5fb0001c08d3ad673f23356f9f677cfe7312430f129644bf67574
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: chromium-by-roket
x-casaos:
  main: chromium
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.chromium/assets/icon.png
  title:
    en_US: Chromium (LinuxServer.io)
  id: by-roket.linuxserver.chromium
  port_map: '3000'
  version: arm64v8-version-d39975b5
  index: /
