name: linuxserver-chromium
services:
  chromium:
    image: linuxserver/chromium:version-7ac003b2@sha256:abc7bd46e865d6b584ad58a52806c2e8ee457743fd3d74af74c87ecfca284c6c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: chromium-by-roket
x-casaos:
  main: chromium
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.chromium/assets/icon.png
  title:
    en_US: Chromium (LinuxServer.io)
  id: by-roket.linuxserver.chromium
  port_map: '3000'
  version: version-7ac003b2
  index: /
