name: linuxserver-limnoria
services:
  limnoria:
    image: linuxserver/limnoria:2026.5.8@sha256:1dc47140c6aadeef48566e29d154c3b2804ae96b1d588f354a26493cae158ba4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/limnoria/config
        target: /config
x-casaos:
  main: limnoria
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.limnoria/assets/icon.png
  title:
    en_US: Limnoria
  port_map: '8080'
  id: by-roket.linuxserver.limnoria
  version: 2026.5.8
  index: /
