name: linuxserver-audacity
services:
  audacity:
    image: linuxserver/audacity:4.0.0@sha256:666e34e6fbd1cb17de4f07713cbfd039975a2ce9f9216f3f21f16a947d97c988
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: audacity-by-roket
x-casaos:
  main: audacity
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.audacity/assets/icon.png
  title:
    en_US: Audacity (LinuxServer.io)
  id: by-roket.linuxserver.audacity
  port_map: '3000'
  version: 4.0.0
  index: /
