name: linuxserver-ppsspp
services:
  ppsspp:
    image: linuxserver/ppsspp:1.20.4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: ppsspp-by-roket
x-casaos:
  main: ppsspp
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ppsspp/assets/icon.png
  title:
    en_US: Ppsspp
  port_map: '3000'
  id: by-roket.linuxserver.ppsspp
  version: 1.20.4
  index: /
