name: linuxserver-bitcoin-knots
services:
  bitcoin-knots:
    image: linuxserver/bitcoin-knots:version-29.4.knots20260508.1-noble1@sha256:6632d680d06a320b2025afa755b6336c93c9f10f4f5aa25ecaecf3bc9b9cd88e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
      - target: 8333
        published: 8333
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: bitcoin-knots-by-roket
x-casaos:
  main: bitcoin-knots
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.bitcoin-knots/assets/icon.png
  title:
    en_US: Bitcoin knots (LinuxServer.io)
  id: by-roket.linuxserver.bitcoin-knots
  port_map: '3000'
  version: version-29.4.knots20260508.1-noble1
  index: /
