name: linuxserver-calligra
services:
  calligra:
    image: linuxserver/calligra:3.2.1@sha256:72a8e91280cbccb1a9678fe1d18f4c815e030b880dfc8e48f4f4fce72fe5a644
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: calligra-by-roket
x-casaos:
  main: calligra
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.calligra/assets/icon.png
  title:
    en_US: Calligra (LinuxServer.io)
  id: by-roket.linuxserver.calligra
  port_map: '3000'
  version: 3.2.1
  index: /
