name: linuxserver-bazarr
services:
  bazarr:
    image: linuxserver/bazarr:1.6.0@sha256:7f238a6aed7fe714814c57ceee28f0c8ada62a8cae55e58ec009140c837609d3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 6767
        published: 6767
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bazarr/config
        target: /config
      - type: bind
        source: /DATA/AppData/bazarr/movies
        target: /movies
      - type: bind
        source: /DATA/AppData/bazarr/tv
        target: /tv
x-casaos:
  main: bazarr
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.bazarr/assets/icon.png
  title:
    en_US: Bazarr
  port_map: '6767'
  id: by-roket.linuxserver.bazarr
  version: 1.6.0
  index: /
