name: linuxserver-jackett
services:
  jackett:
    image: linuxserver/jackett:0.24.2531@sha256:84a5a3b4382508e8bf5cbca23003e008c3dc0ae093d301764de0fa5fd745d37e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      AUTO_UPDATE: ''
      RUN_OPTS: ''
    ports:
      - target: 9117
        published: 9117
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: jackett-by-roket
x-casaos:
  main: jackett
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.jackett/assets/icon.png
  title:
    en_US: Jackett (LinuxServer.io)
  id: by-roket.linuxserver.jackett
  port_map: '9117'
  version: 0.24.2531
  index: /
