name: linuxserver-jackett
services:
  jackett:
    image: linuxserver/jackett:0.24.2467@sha256:a3a799c97b0cefc2bfd535dc367f71ce825fa5785b48f545c8f8c50d693eb58f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      AUTO_UPDATE: ''
      RUN_OPTS: ''
    ports:
      - target: 9117
        published: 9117
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: jackett-by-roket
x-casaos:
  main: jackett
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.jackett/assets/icon.png
  title:
    en_US: Jackett
  port_map: '9117'
  id: by-roket.linuxserver.jackett
  version: 0.24.2467
  index: /
