name: linuxserver-ffmpeg
services:
  ffmpeg:
    image: linuxserver/ffmpeg:8.1.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: ffmpeg-by-roket
x-casaos:
  main: ffmpeg
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ffmpeg/assets/icon.png
  title:
    en_US: Ffmpeg
  port_map: '80'
  id: by-roket.linuxserver.ffmpeg
  version: 8.1.2
  index: /
