name: linuxserver-pycharm
services:
  pycharm:
    image: linuxserver/pycharm:2026.2.1@sha256:0c1f0fc48d9ab21ca9697e6601769303a4b3f0fbca1b3778e8b03a938d4c4aaa
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: pycharm-by-roket
x-casaos:
  main: pycharm
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.pycharm/assets/icon.png
  title:
    en_US: Pycharm (LinuxServer.io)
  id: by-roket.linuxserver.pycharm
  port_map: '3000'
  version: 2026.2.1
  index: /
