name: linuxserver-changedetection-io
services:
  changedetection-io:
    image: linuxserver/changedetection.io:0.60.3@sha256:18ee44d62960ec01e45d498ed240ab91313c24a9eadd01d444ac0aba0fece9d0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
      PLAYWRIGHT_DRIVER_URL: ''
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: changedetection-io-by-roket
x-casaos:
  main: changedetection-io
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.changedetection-io/assets/icon.png
  title:
    en_US: Changedetection. Io (LinuxServer.io)
  id: by-roket.linuxserver.changedetection-io
  port_map: '5000'
  version: 0.60.3
  index: /
