name: linuxserver-sabnzbd
services:
  sabnzbd:
    image: linuxserver/sabnzbd:5.1.2@sha256:f67574eff28a0ca79930428694517eeaa1f033985e986cc0f2bac338b670f700
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/incomplete-downloads
        target: /incomplete-downloads
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: sabnzbd-by-roket
x-casaos:
  main: sabnzbd
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.sabnzbd/assets/icon.png
  title:
    en_US: Sabnzbd (LinuxServer.io)
  id: by-roket.linuxserver.sabnzbd
  port_map: '8080'
  version: 5.1.2
  index: /
