name: linuxserver-speedtest-tracker
services:
  app:
    image: linuxserver/speedtest-tracker:1.15.0@sha256:5bef203d0d9e2f0a061949b81752dfa9472a2033a694a7481a7b7ca08dfff3f2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APP_KEY: ''
      APP_URL: ''
      DB_CONNECTION: ''
      SPEEDTEST_SCHEDULE: ''
      SPEEDTEST_SERVERS: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_DATABASE: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DISPLAY_TIMEZONE: ''
      PRUNE_RESULTS_OLDER_THAN: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/speedtest-tracker/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.speedtest-tracker/assets/icon.png
  title:
    en_US: Speedtest tracker
  port_map: '80'
  id: by-roket.linuxserver.speedtest-tracker
  version: 1.15.0
  index: /
