name: linuxserver-overseerr
services:
  app:
    image: linuxserver/overseerr:1.33.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 5055
        published: 5055
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/overseerr/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.overseerr/assets/icon.png
  title:
    en_US: Overseerr
  port_map: '5055'
  id: by-roket.linuxserver.overseerr
  version: 1.33.2
  index: /
