name: linuxserver-gimp
services:
  gimp:
    image: linuxserver/gimp:version-22638545
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: gimp-by-roket
x-casaos:
  main: gimp
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.gimp/assets/icon.png
  title:
    en_US: Gimp (LinuxServer.io)
  id: by-roket.linuxserver.gimp
  port_map: '3000'
  version: version-22638545
  index: /
