name: linuxserver-kicad
services:
  kicad:
    image: linuxserver/kicad:10.0.3@sha256:72ca3c242668b84d4095a901afd1f473344c2ea8ab932f755993c7ac9c70db27
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kicad/config
        target: /config
x-casaos:
  main: kicad
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.kicad/assets/icon.png
  title:
    en_US: Kicad
  port_map: '3000'
  id: by-roket.linuxserver.kicad
  version: 10.0.3
  index: /
