name: linuxserver-tvheadend
services:
  tvheadend:
    image: linuxserver/tvheadend:version-fcd987f0@sha256:ea93fce7390df98a17c99f77a3c75d82cefa5e3de6fc2bbb27c1ada99c96ad29
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RUN_OPTS: ''
    ports:
      - target: 9981
        published: 9981
        protocol: tcp
      - target: 9982
        published: 9982
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/recordings
        target: /recordings
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    container_name: tvheadend-by-roket
x-casaos:
  main: tvheadend
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.tvheadend/assets/icon.png
  title:
    en_US: Tvheadend
  id: by-roket.linuxserver.tvheadend
  version: version-fcd987f0
  index: /
  port_map: '9981'
