name: linuxserver-ci
services:
  ci:
    image: linuxserver/ci:b1ca9f98-ls65@sha256:6f85f4ab41a8c78ae5636a594281d3f97ae69fd269aac46017b47ac786a8f2fd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: ci-by-roket
x-casaos:
  main: ci
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ci/assets/icon.svg
  title:
    en_US: Ci
    zh_CN: Ci
    ca_ES: Ci
    cs_CZ: Ci
    da_DK: Ci
    de_DE: Ci
    el_GR: Ci
    en_GB: Ci
    es_ES: Ci
    fr_FR: Ci
    ga_IE: Ci
    hr_HR: Ci
    hu_HU: Ci
    it_IT: Ci
    ja_JP: Ci
    ko_KR: Ci
    ml_IN: Ci
    nb_NO: Ci
    nl_NL: Ci
    pl_PL: Ci
    pt_BR: Ci
    ro_RO: Ci
    ru_RU: Ci
    sk_SK: Ci
    sv_SE: Ci
    tr_TR: Ci
    zh_TW: Ci
  port_map: '80'
  id: by-roket.linuxserver.ci
  version: b1ca9f98-ls65
  index: /
