name: linuxserver-duckstation
services:
  duckstation:
    image: linuxserver/duckstation:version-latest@sha256:98c5861ea4d9281060a6dfb6cddd8fc72090439a38dadd1f7ded7090096334bf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/duckstation/config
        target: /config
x-casaos:
  main: duckstation
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.duckstation/assets/icon.png
  title:
    en_US: Duckstation
  port_map: '3000'
  id: by-roket.linuxserver.duckstation
  version: version-latest
  index: /
