name: linuxserver-chrome
services:
  chrome:
    image: linuxserver/chrome:153.0.8010@sha256:801c26f5f64d20296790ff2c2dba846ac8d0498c0b1561d53fd0b34a9e07af2e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: chrome-by-roket
x-casaos:
  main: chrome
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.chrome/assets/icon.png
  title:
    en_US: Chrome (LinuxServer.io)
  id: by-roket.linuxserver.chrome
  port_map: '3000'
  version: 153.0.8010
  index: /
