name: linuxserver-gitqlient
services:
  gitqlient:
    image: linuxserver/gitqlient:1.6.3@sha256:deef6f7fbf746d825513a4ad5b270417bbb117cb17e991a4398cdf7efb5e3433
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: gitqlient-by-roket
x-casaos:
  main: gitqlient
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.gitqlient/assets/icon.png
  title:
    en_US: Gitqlient (LinuxServer.io)
  id: by-roket.linuxserver.gitqlient
  port_map: '3000'
  version: 1.6.3
  index: /
