name: linuxserver-weixin
services:
  weixin:
    image: linuxserver/weixin:version-93cea97f@sha256:05690fa4fec90f21b82c31f186e11085522261a3c65e35681e3089449957c6a5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: weixin-by-roket
x-casaos:
  main: weixin
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.weixin/assets/icon.png
  title:
    en_US: Weixin
  port_map: '3000'
  id: by-roket.linuxserver.weixin
  version: version-93cea97f
  index: /
