name: linuxserver-rsnapshot
services:
  rsnapshot:
    image: linuxserver/rsnapshot:1.4.5@sha256:5e00cfb9366b7613c0e147dccbb3886f3f806b5b303ea2688fe6ab25ce634265
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rsnapshot/config
        target: /config
      - type: bind
        source: /DATA/AppData/rsnapshot/.snapshots
        target: /.snapshots
      - type: bind
        source: /DATA/AppData/rsnapshot/data
        target: /data
x-casaos:
  main: rsnapshot
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rsnapshot/assets/icon.png
  title:
    en_US: Rsnapshot
  port_map: '80'
  id: by-roket.linuxserver.rsnapshot
  version: 1.4.5
  index: /
