name: linuxserver-rsnapshot
services:
  app:
    image: linuxserver/rsnapshot:1.4.5@sha256:e412a7194ac9e9a1ffeea791d6d6e8a64cb06c16c6a09a8deae7c299482fc945
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rsnapshot/config
        target: /config
      - type: bind
        source: /DATA/AppData/rsnapshot/.snapshots
        target: /.snapshots
      - type: bind
        source: /DATA/AppData/rsnapshot/data
        target: /data
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rsnapshot/assets/icon.png
  title:
    en_US: Rsnapshot
  port_map: '80'
  id: by-roket.linuxserver.rsnapshot
  version: 1.4.5
  index: /
