name: linuxserver-jenkins-builder
services:
  jenkins-builder:
    image: linuxserver/jenkins-builder:version-4f81ddbe@sha256:9b231fb997828360cb7a92ab55edcd378928eaad414ea63f1a1c41b02c502674
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: jenkins-builder-by-roket
x-casaos:
  main: jenkins-builder
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.jenkins-builder/assets/icon.png
  title:
    en_US: Jenkins builder
  port_map: '80'
  id: by-roket.linuxserver.jenkins-builder
  version: version-4f81ddbe
  index: /
