name: linuxserver-babybuddy
services:
  babybuddy:
    image: linuxserver/babybuddy:2.10.0@sha256:dba8d4cde86878ec9f06172b00ac72435b5607314d3e956db7813f8e48f4b1fb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CSRF_TRUSTED_ORIGINS: ''
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: babybuddy-by-roket
x-casaos:
  main: babybuddy
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.babybuddy/assets/icon.png
  title:
    en_US: Babybuddy (LinuxServer.io)
  id: by-roket.linuxserver.babybuddy
  port_map: '8000'
  version: 2.10.0
  index: /
