name: linuxserver-babybuddy
services:
  babybuddy:
    image: linuxserver/babybuddy:2.10.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CSRF_TRUSTED_ORIGINS: ''
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/babybuddy/config
        target: /config
x-casaos:
  main: babybuddy
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.babybuddy/assets/icon.png
  title:
    en_US: Babybuddy
  port_map: '8000'
  id: by-roket.linuxserver.babybuddy
  version: 2.10.0
  index: /
