name: linuxserver-retroarch
services:
  app:
    image: linuxserver/retroarch:1.22.2@sha256:3c6845ab66ec0c1dc65172949c53e301d90742bad65397d0b11d52e22f251b66
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/retroarch/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.retroarch/assets/icon.png
  title:
    en_US: Retroarch
  port_map: '3000'
  id: by-roket.linuxserver.retroarch
  version: 1.22.2
  index: /
