name: linuxserver-retroarch
services:
  retroarch:
    image: linuxserver/retroarch:1.22.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: retroarch-by-roket
x-casaos:
  main: retroarch
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.retroarch/assets/icon.png
  title:
    en_US: Retroarch (LinuxServer.io)
  id: by-roket.linuxserver.retroarch
  port_map: '3000'
  version: 1.22.2
  index: /
