name: linuxserver-lychee
services:
  lychee:
    image: linuxserver/lychee:7.7.4@sha256:b4aaa932adc87f914c575bc3e3662835522a62e76be6e0590149d0d9dae40d66
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_CONNECTION: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_DATABASE: ''
      APP_NAME: ''
      APP_URL: ''
      TRUSTED_PROXIES: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/pictures
        target: /pictures
    container_name: lychee-by-roket
x-casaos:
  main: lychee
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.lychee/assets/icon.png
  title:
    en_US: Lychee
  port_map: '80'
  id: by-roket.linuxserver.lychee
  version: 7.7.4
  index: /
