name: linuxserver-lychee
services:
  lychee:
    image: linuxserver/lychee:7.8.0@sha256:73a396c0b0125b1251d56fab0b55bcf4a9d167813de331b339a7e26457951645
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_CONNECTION: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_DATABASE: ''
      APP_NAME: ''
      APP_URL: ''
      TRUSTED_PROXIES: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/pictures
        target: /pictures
    container_name: lychee-by-roket
x-casaos:
  main: lychee
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.lychee/assets/icon.png
  title:
    en_US: Lychee (LinuxServer.io)
  id: by-roket.linuxserver.lychee
  port_map: '80'
  version: 7.8.0
  index: /
