name: linuxserver-nginx
services:
  nginx:
    image: linuxserver/nginx:1.30.4@sha256:5a7f215a3ce4e4b5d77d59b3f5c50d0adb018f780a423c4759f1d7f184336525
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      NGINX_AUTORELOAD: ''
      NGINX_AUTORELOAD_WATCHLIST: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: nginx-by-roket
x-casaos:
  main: nginx
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.nginx/assets/icon.png
  title:
    en_US: Nginx
  port_map: '80'
  id: by-roket.linuxserver.nginx
  version: 1.30.4
  index: /
