name: linuxserver-doublecommander
services:
  doublecommander:
    image: linuxserver/doublecommander:arm64v8-version-47f5ef2f@sha256:ab8182c039768ce343369bec9bd2249a852b6144b86efc1bf64571a0bc7be10f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: doublecommander-by-roket
x-casaos:
  main: doublecommander
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.doublecommander/assets/icon.png
  title:
    en_US: Doublecommander (LinuxServer.io)
  id: by-roket.linuxserver.doublecommander
  port_map: '3000'
  version: arm64v8-version-47f5ef2f
  index: /
