name: linuxserver-openssh-server
services:
  openssh-server:
    image: linuxserver/openssh-server:version-10.3_p1-r1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PUBLIC_KEY: ''
      PUBLIC_KEY_FILE: ''
      PUBLIC_KEY_DIR: ''
      PUBLIC_KEY_URL: ''
      SUDO_ACCESS: ''
      PASSWORD_ACCESS: ''
      USER_PASSWORD: ''
      USER_PASSWORD_FILE: ''
      USER_NAME: ''
      LOG_STDOUT: ''
    ports:
      - target: 2222
        published: 2222
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: openssh-server-by-roket
x-casaos:
  main: openssh-server
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.openssh-server/assets/icon.png
  title:
    en_US: Openssh server (LinuxServer.io)
  id: by-roket.linuxserver.openssh-server
  port_map: '2222'
  version: version-10.3_p1-r1
  index: /
