name: linuxserver-hishtory-server
services:
  hishtory-server:
    image: linuxserver/hishtory-server:0.335.20260821@sha256:d43c7ebe2ef79f0d9a8a9d0c0537a4400c286650b29cfabcbb7836ed6161f4b7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HISHTORY_POSTGRES_DB: ''
      HISHTORY_SQLITE_DB: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: hishtory-server-by-roket
x-casaos:
  main: hishtory-server
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.hishtory-server/assets/icon.png
  title:
    en_US: Hishtory server
  port_map: '8080'
  id: by-roket.linuxserver.hishtory-server
  version: 0.335.20260821
  index: /
