name: linuxserver-spotube
services:
  spotube:
    image: linuxserver/spotube:5.1.2@sha256:252a41ba0639b33810656f4695ea2ae868863901d8d556764833e8d1e17cc728
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: spotube-by-roket
x-casaos:
  main: spotube
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.spotube/assets/icon.png
  title:
    en_US: Spotube (LinuxServer.io)
  id: by-roket.linuxserver.spotube
  port_map: '3000'
  version: 5.1.2
  index: /
