name: linuxserver-airsonic-advanced
services:
  airsonic-advanced:
    image: linuxserver/airsonic-advanced:11.1.4@sha256:94feab26ed64f9ef69b70d4010c8763112da75460d335fedd9acaaf7b515c1a9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONTEXT_PATH: ''
      JAVA_OPTS: ''
    ports:
      - target: 4040
        published: 4040
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/music
        target: /music
      - type: bind
        source: /DATA/AppData/$AppID/playlists
        target: /playlists
      - type: bind
        source: /DATA/AppData/$AppID/podcasts
        target: /podcasts
      - type: bind
        source: /DATA/AppData/$AppID/media
        target: /media
    container_name: airsonic-advanced-by-roket
x-casaos:
  main: airsonic-advanced
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.airsonic-advanced/assets/icon.png
  title:
    en_US: Airsonic advanced (LinuxServer.io)
  id: by-roket.linuxserver.airsonic-advanced
  port_map: '4040'
  version: 11.1.4
  index: /
