name: linuxserver-yaak
services:
  yaak:
    image: linuxserver/yaak:2026.6.0@sha256:af85f25adb4af4270c8af3d9e7c9a9c51c18879f3569de7c157a50a65e7c63d3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: yaak-by-roket
x-casaos:
  main: yaak
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.yaak/assets/icon.png
  title:
    en_US: Yaak (LinuxServer.io)
  id: by-roket.linuxserver.yaak
  port_map: '3000'
  version: 2026.6.0
  index: /
