name: linuxserver-yaak
services:
  yaak:
    image: linuxserver/yaak:2026.7.0@sha256:0e7f90a522fbd2fe74c60dc4bb89bf9a6a62adac7ae0e19d0983f1509744dd32
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: yaak-by-roket
x-casaos:
  main: yaak
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.yaak/assets/icon.png
  title:
    en_US: Yaak (LinuxServer.io)
  id: by-roket.linuxserver.yaak
  port_map: '3000'
  version: 2026.7.0
  index: /
