name: linuxserver-yaak
services:
  yaak:
    image: linuxserver/yaak:2026.7.1@sha256:759a1a54b97acc6551c2a48e6b7aa4b351ec2dd95737ff96af2ac2bcc9144020
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: yaak-by-roket
x-casaos:
  main: yaak
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.yaak/assets/icon.png
  title:
    en_US: Yaak (LinuxServer.io)
  id: by-roket.linuxserver.yaak
  port_map: '3000'
  version: 2026.7.1
  index: /
