name: linuxserver-firefox
services:
  firefox:
    image: linuxserver/firefox:2.2404.1@sha256:3068a1d565e220f0049dc0e0682af66eb381a8f348e18f3845baee36ca6c2e50
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FIREFOX_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: firefox-by-roket
x-casaos:
  main: firefox
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.firefox/assets/icon.png
  title:
    en_US: Firefox (LinuxServer.io)
  id: by-roket.linuxserver.firefox
  port_map: '3000'
  version: 2.2404.1
  index: /
