name: linuxserver-eden
services:
  eden:
    image: linuxserver/eden:0.2.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: eden-by-roket
x-casaos:
  main: eden
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.eden/assets/icon.png
  title:
    en_US: Eden (LinuxServer.io)
    ca_ES: Eden (LinuxServer.io)
    cs_CZ: Eden (LinuxServer.io)
    da_DK: Eden (LinuxServer.io)
    de_DE: Eden (LinuxServer.io)
    el_GR: Eden (LinuxServer.io)
    en_GB: Eden (LinuxServer.io)
    es_ES: Eden (LinuxServer.io)
    fr_FR: Eden (LinuxServer.io)
    ga_IE: Eden (LinuxServer.io)
    hr_HR: Eden (LinuxServer.io)
    hu_HU: Eden (LinuxServer.io)
    it_IT: Eden (LinuxServer.io)
    ja_JP: Eden (LinuxServer.io)
    ko_KR: Eden (LinuxServer.io)
    ml_IN: Eden (LinuxServer.io)
    nb_NO: Eden (LinuxServer.io)
    nl_NL: Eden (LinuxServer.io)
    pl_PL: Eden (LinuxServer.io)
    pt_BR: Eden (LinuxServer.io)
    ro_RO: Eden (LinuxServer.io)
    ru_RU: Eden (LinuxServer.io)
    sk_SK: Eden (LinuxServer.io)
    sv_SE: Eden (LinuxServer.io)
    tr_TR: Eden (LinuxServer.io)
    zh_CN: Eden（LinuxServer.io）
    zh_TW: Eden（LinuxServer.io）
  id: by-roket.linuxserver.eden
  port_map: '3000'
  version: 0.2.1
  index: /
