name: linuxserver-wireshark
services:
  wireshark:
    image: linuxserver/wireshark:4.6.6@sha256:28f116eb10f4890e433f5dab431ef385bf4c4c0de193c9b0f6c48b46442b602a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: wireshark-by-roket
x-casaos:
  main: wireshark
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.wireshark/assets/icon.png
  title:
    en_US: Wireshark (LinuxServer.io)
    ca_ES: Wireshark (LinuxServer.io)
    cs_CZ: Wireshark (LinuxServer.io)
    da_DK: Wireshark (LinuxServer.io)
    de_DE: Wireshark (LinuxServer.io)
    el_GR: Wireshark (LinuxServer.io)
    en_GB: Wireshark (LinuxServer.io)
    es_ES: Wireshark (LinuxServer.io)
    fr_FR: Wireshark (LinuxServer.io)
    ga_IE: Wireshark (LinuxServer.io)
    hr_HR: Wireshark (LinuxServer.io)
    hu_HU: Wireshark (LinuxServer.io)
    it_IT: Wireshark (LinuxServer.io)
    ja_JP: Wireshark (LinuxServer.io)
    ko_KR: Wireshark (LinuxServer.io)
    ml_IN: Wireshark (LinuxServer.io)
    nb_NO: Wireshark (LinuxServer.io)
    nl_NL: Wireshark (LinuxServer.io)
    pl_PL: Wireshark (LinuxServer.io)
    pt_BR: Wireshark (LinuxServer.io)
    ro_RO: Wireshark (LinuxServer.io)
    ru_RU: Wireshark (LinuxServer.io)
    sk_SK: Wireshark (LinuxServer.io)
    sv_SE: Wireshark (LinuxServer.io)
    tr_TR: Wireshark (LinuxServer.io)
    zh_CN: Wireshark（LinuxServer.io）
    zh_TW: Wireshark（LinuxServer.io）
  id: by-roket.linuxserver.wireshark
  port_map: '80'
  version: 4.6.6
  index: /
