name: linuxserver-wireshark
services:
  wireshark:
    image: linuxserver/wireshark:4.6.6@sha256:5b6658d5c9cdb9a53f94f3579583fb2993f3876f2eb4777001ecbd2f592fec43
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: wireshark-by-roket
x-casaos:
  main: wireshark
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.wireshark/assets/icon.png
  title:
    en_US: Wireshark
  port_map: '80'
  id: by-roket.linuxserver.wireshark
  version: 4.6.6
  index: /
