name: linuxserver-pcsx2
services:
  pcsx2:
    image: linuxserver/pcsx2:2.6.3@sha256:aff0feb613332e6779f48eb142948b153fecb4827634143813d52fb91e044b43
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: pcsx2-by-roket
x-casaos:
  main: pcsx2
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.pcsx2/assets/icon.png
  title:
    en_US: Pcsx2 (LinuxServer.io)
  id: by-roket.linuxserver.pcsx2
  port_map: '3000'
  version: 2.6.3
  index: /
