name: linuxserver-cura
services:
  cura:
    image: linuxserver/cura:5.13.0@sha256:5357fcadb41b581a8a84df930fcfb1b40dfeb5b8532cf9dd392a15a3005b98f7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: cura-by-roket
x-casaos:
  main: cura
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.cura/assets/icon.png
  title:
    en_US: Cura (LinuxServer.io)
    ca_ES: Cura (LinuxServer.io)
    cs_CZ: Cura (LinuxServer.io)
    da_DK: Cura (LinuxServer.io)
    de_DE: Cura (LinuxServer.io)
    el_GR: Cura (LinuxServer.io)
    en_GB: Cura (LinuxServer.io)
    es_ES: Cura (LinuxServer.io)
    fr_FR: Cura (LinuxServer.io)
    ga_IE: Cura (LinuxServer.io)
    hr_HR: Cura (LinuxServer.io)
    hu_HU: Cura (LinuxServer.io)
    it_IT: Cura (LinuxServer.io)
    ja_JP: Cura (LinuxServer.io)
    ko_KR: Cura (LinuxServer.io)
    ml_IN: Cura (LinuxServer.io)
    nb_NO: Cura (LinuxServer.io)
    nl_NL: Cura (LinuxServer.io)
    pl_PL: Cura (LinuxServer.io)
    pt_BR: Cura (LinuxServer.io)
    ro_RO: Cura (LinuxServer.io)
    ru_RU: Cura (LinuxServer.io)
    sk_SK: Cura (LinuxServer.io)
    sv_SE: Cura (LinuxServer.io)
    tr_TR: Cura (LinuxServer.io)
    zh_CN: Cura（LinuxServer.io）
    zh_TW: Cura（LinuxServer.io）
  id: by-roket.linuxserver.cura
  port_map: '3000'
  version: 5.13.0
  index: /
