name: linuxserver-cura
services:
  cura:
    image: linuxserver/cura:5.13.0@sha256:5357fcadb41b581a8a84df930fcfb1b40dfeb5b8532cf9dd392a15a3005b98f7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: cura-by-roket
x-casaos:
  main: cura
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.cura/assets/icon.png
  title:
    en_US: Cura (LinuxServer.io)
  id: by-roket.linuxserver.cura
  port_map: '3000'
  version: 5.13.0
  index: /
