name: linuxserver-pyload-ng
services:
  pyload-ng:
    image: linuxserver/pyload-ng:0.5.0@sha256:881e5bd97524a6174952a42b4cd39356f6038524819afaa6bff0981bd65f6420
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 9666
        published: 9666
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: pyload-ng-by-roket
x-casaos:
  main: pyload-ng
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.pyload-ng/assets/icon.png
  title:
    en_US: Pyload ng
  port_map: '8000'
  id: by-roket.linuxserver.pyload-ng
  version: 0.5.0
  index: /
