name: linuxserver-kali-linux
services:
  kali-linux:
    image: linuxserver/kali-linux:version-b6cbe11b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: kali-linux-by-roket
x-casaos:
  main: kali-linux
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.kali-linux/assets/icon.png
  title:
    en_US: Kali linux (LinuxServer.io)
  id: by-roket.linuxserver.kali-linux
  port_map: '3000'
  version: version-b6cbe11b
  index: /
