name: linuxserver-kali-linux
services:
  kali-linux:
    image: linuxserver/kali-linux:version-3ed8e88f@sha256:d090b23aae40d339f1a404f294c94f6eb05872236083b3db58b328627a55ee3b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: kali-linux-by-roket
x-casaos:
  main: kali-linux
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.kali-linux/assets/icon.png
  title:
    en_US: Kali linux (LinuxServer.io)
    ca_ES: Kali linux (LinuxServer.io)
    cs_CZ: Kali linux (LinuxServer.io)
    da_DK: Kali linux (LinuxServer.io)
    de_DE: Kali linux (LinuxServer.io)
    el_GR: Kali linux (LinuxServer.io)
    en_GB: Kali linux (LinuxServer.io)
    es_ES: Kali linux (LinuxServer.io)
    fr_FR: Kali linux (LinuxServer.io)
    ga_IE: Kali linux (LinuxServer.io)
    hr_HR: Kali linux (LinuxServer.io)
    hu_HU: Kali linux (LinuxServer.io)
    it_IT: Kali linux (LinuxServer.io)
    ja_JP: Kali linux (LinuxServer.io)
    ko_KR: Kali linux (LinuxServer.io)
    ml_IN: Kali linux (LinuxServer.io)
    nb_NO: Kali linux (LinuxServer.io)
    nl_NL: Kali linux (LinuxServer.io)
    pl_PL: Kali linux (LinuxServer.io)
    pt_BR: Kali linux (LinuxServer.io)
    ro_RO: Kali linux (LinuxServer.io)
    ru_RU: Kali linux (LinuxServer.io)
    sk_SK: Kali linux (LinuxServer.io)
    sv_SE: Kali linux (LinuxServer.io)
    tr_TR: Kali linux (LinuxServer.io)
    zh_CN: Kali linux（LinuxServer.io）
    zh_TW: Kali linux（LinuxServer.io）
  id: by-roket.linuxserver.kali-linux
  port_map: '3000'
  version: version-3ed8e88f
  index: /
