name: linuxserver-qbittorrent
services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.2.3@sha256:5889d4df956636ea174946efa58921aba7526077a784980d18daf283a310e784
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      WEBUI_PORT: ''
      TORRENTING_PORT: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 6881
        published: 6881
        protocol: tcp
      - target: 6881
        published: 6881
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: qbittorrent-by-roket
x-casaos:
  main: qbittorrent
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.qbittorrent/assets/icon.png
  title:
    en_US: Qbittorrent
  port_map: '8080'
  id: by-roket.linuxserver.qbittorrent
  version: 5.2.3
  index: /
