name: linuxserver-onlyoffice
services:
  onlyoffice:
    image: linuxserver/onlyoffice:9.4.0@sha256:bb0241da8aea5d13fa1649bdc827f8eb02c1db9b69f7445d7bc9cc0ac766a4df
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: onlyoffice-by-roket
x-casaos:
  main: onlyoffice
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.onlyoffice/assets/icon.png
  title:
    en_US: Onlyoffice (LinuxServer.io)
  id: by-roket.linuxserver.onlyoffice
  port_map: '3000'
  version: 9.4.0
  index: /
