name: linuxserver-onlyoffice
services:
  onlyoffice:
    image: linuxserver/onlyoffice:9.4.0@sha256:bb0241da8aea5d13fa1649bdc827f8eb02c1db9b69f7445d7bc9cc0ac766a4df
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: onlyoffice-by-roket
x-casaos:
  main: onlyoffice
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.onlyoffice/assets/icon.png
  title:
    en_US: Onlyoffice (LinuxServer.io)
    ca_ES: Onlyoffice (LinuxServer.io)
    cs_CZ: Onlyoffice (LinuxServer.io)
    da_DK: Onlyoffice (LinuxServer.io)
    de_DE: Onlyoffice (LinuxServer.io)
    el_GR: Onlyoffice (LinuxServer.io)
    en_GB: Onlyoffice (LinuxServer.io)
    es_ES: Onlyoffice (LinuxServer.io)
    fr_FR: Onlyoffice (LinuxServer.io)
    ga_IE: Onlyoffice (LinuxServer.io)
    hr_HR: Onlyoffice (LinuxServer.io)
    hu_HU: Onlyoffice (LinuxServer.io)
    it_IT: Onlyoffice (LinuxServer.io)
    ja_JP: Onlyoffice (LinuxServer.io)
    ko_KR: Onlyoffice (LinuxServer.io)
    ml_IN: Onlyoffice (LinuxServer.io)
    nb_NO: Onlyoffice (LinuxServer.io)
    nl_NL: Onlyoffice (LinuxServer.io)
    pl_PL: Onlyoffice (LinuxServer.io)
    pt_BR: Onlyoffice (LinuxServer.io)
    ro_RO: Onlyoffice (LinuxServer.io)
    ru_RU: Onlyoffice (LinuxServer.io)
    sk_SK: Onlyoffice (LinuxServer.io)
    sv_SE: Onlyoffice (LinuxServer.io)
    tr_TR: Onlyoffice (LinuxServer.io)
    zh_CN: Onlyoffice（LinuxServer.io）
    zh_TW: Onlyoffice（LinuxServer.io）
  id: by-roket.linuxserver.onlyoffice
  port_map: '3000'
  version: 9.4.0
  index: /
