name: linuxserver-mysql-workbench
services:
  mysql-workbench:
    image: linuxserver/mysql-workbench:8.0.47@sha256:555a7d31bea21f39ecf457f294624d58de418a9197e9f08ca3311849d6c915f4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: mysql-workbench-by-roket
x-casaos:
  main: mysql-workbench
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.mysql-workbench/assets/icon.png
  title:
    en_US: Mysql workbench (LinuxServer.io)
  id: by-roket.linuxserver.mysql-workbench
  port_map: '3000'
  version: 8.0.47
  index: /
