name: linuxserver-blade-of-agony
services:
  blade-of-agony:
    image: linuxserver/blade-of-agony:3.1.20260903
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: blade-of-agony-by-roket
x-casaos:
  main: blade-of-agony
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.blade-of-agony/assets/icon.png
  title:
    en_US: Blade of-agony (LinuxServer.io)
  id: by-roket.linuxserver.blade-of-agony
  port_map: '3000'
  version: 3.1.20260903
  index: /
