name: linuxserver-blade-of-agony
services:
  blade-of-agony:
    image: linuxserver/blade-of-agony:3.1.20260917
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: blade-of-agony-by-roket
x-casaos:
  main: blade-of-agony
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.blade-of-agony/assets/icon.png
  title:
    en_US: Blade of-agony (LinuxServer.io)
    ca_ES: Blade of-agony (LinuxServer.io)
    cs_CZ: Blade of-agony (LinuxServer.io)
    da_DK: Blade of-agony (LinuxServer.io)
    de_DE: Blade of-agony (LinuxServer.io)
    el_GR: Blade of-agony (LinuxServer.io)
    en_GB: Blade of-agony (LinuxServer.io)
    es_ES: Blade of-agony (LinuxServer.io)
    fr_FR: Blade of-agony (LinuxServer.io)
    ga_IE: Blade of-agony (LinuxServer.io)
    hr_HR: Blade of-agony (LinuxServer.io)
    hu_HU: Blade of-agony (LinuxServer.io)
    it_IT: Blade of-agony (LinuxServer.io)
    ja_JP: Blade of-agony (LinuxServer.io)
    ko_KR: Blade of-agony (LinuxServer.io)
    ml_IN: Blade of-agony (LinuxServer.io)
    nb_NO: Blade of-agony (LinuxServer.io)
    nl_NL: Blade of-agony (LinuxServer.io)
    pl_PL: Blade of-agony (LinuxServer.io)
    pt_BR: Blade of-agony (LinuxServer.io)
    ro_RO: Blade of-agony (LinuxServer.io)
    ru_RU: Blade of-agony (LinuxServer.io)
    sk_SK: Blade of-agony (LinuxServer.io)
    sv_SE: Blade of-agony (LinuxServer.io)
    tr_TR: Blade of-agony (LinuxServer.io)
    zh_CN: Blade of-agony（LinuxServer.io）
    zh_TW: Blade of-agony（LinuxServer.io）
  id: by-roket.linuxserver.blade-of-agony
  port_map: '3000'
  version: 3.1.20260917
  index: /
