name: linuxserver-ddclient
services:
  app:
    image: linuxserver/ddclient:4.0.0@sha256:860ab1c0229712747d4abd13b520043c791d3cd97e2bd217788ac3f2ee4c73c5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ddclient/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ddclient/assets/icon.png
  title:
    en_US: Ddclient
  port_map: '80'
  id: by-roket.linuxserver.ddclient
  version: 4.0.0
  index: /
