name: linuxserver-lm-studio
services:
  lm-studio:
    image: linuxserver/lm-studio:version-2026-09-04@sha256:c7bd9df98e555e61e9645c4bf9048efe350f9b9a3cc3caeda3e0017051c7ee3b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: lm-studio-by-roket
x-casaos:
  main: lm-studio
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.lm-studio/assets/icon.png
  title:
    en_US: Lm studio (LinuxServer.io)
  id: by-roket.linuxserver.lm-studio
  port_map: '3000'
  version: version-2026-09-04
  index: /
