name: linuxserver-lm-studio
services:
  lm-studio:
    image: linuxserver/lm-studio:2026-08-21-ls23@sha256:62e4d135483461d4bbf33a7f145943bd372553f6da3473b4fb077c07f66a8d0a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: lm-studio-by-roket
x-casaos:
  main: lm-studio
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.lm-studio/assets/icon.png
  title:
    en_US: Lm studio
  port_map: '3000'
  id: by-roket.linuxserver.lm-studio
  version: 2026-08-21-ls23
  index: /
