name: linuxserver-thunderbird
services:
  thunderbird:
    image: linuxserver/thunderbird:1140.15.0@sha256:45e50cc02cee7a80ad51567282242e2a7614bbcff569390839d28811adfb7acf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: thunderbird-by-roket
x-casaos:
  main: thunderbird
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.thunderbird/assets/icon.png
  title:
    en_US: Thunderbird (LinuxServer.io)
  id: by-roket.linuxserver.thunderbird
  port_map: '3000'
  version: 1140.15.0
  index: /
