name: linuxserver-lazylibrarian
services:
  lazylibrarian:
    image: linuxserver/lazylibrarian:version-31bc5e56@sha256:f187bb690488eb8369110378b3bac5d7ace67c2d996013f0d56dd01665ec3f18
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: ''
    ports:
      - target: 5299
        published: 5299
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/$AppID/books
        target: /books
    container_name: lazylibrarian-by-roket
x-casaos:
  main: lazylibrarian
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.lazylibrarian/assets/icon.png
  title:
    en_US: Lazylibrarian (LinuxServer.io)
  id: by-roket.linuxserver.lazylibrarian
  port_map: '5299'
  version: version-31bc5e56
  index: /
