name: linuxserver-mariadb
services:
  mariadb:
    image: linuxserver/mariadb:11.8.8@sha256:37aa96a86446ca0cb9033f381819ff130e61e15ff3d59df29e52a8bfcc0fe0d9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: ''
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
      REMOTE_SQL: ''
      CLI_OPTS: ''
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: mariadb-by-roket
x-casaos:
  main: mariadb
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.mariadb/assets/icon.png
  title:
    en_US: Mariadb (LinuxServer.io)
  id: by-roket.linuxserver.mariadb
  port_map: '3306'
  version: 11.8.8
  index: /
