name: linuxserver-foldingathome
services:
  foldingathome:
    image: linuxserver/foldingathome:8.5.6@sha256:7c2ce87600dff7ddcc435957cb01c9c040f779790a3d8af61097f9fd7714d3e6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ACCOUNT_TOKEN: ''
      MACHINE_NAME: ''
      CLI_ARGS: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 7396
        published: 7396
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: foldingathome-by-roket
x-casaos:
  main: foldingathome
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.foldingathome/assets/icon.png
  title:
    en_US: Foldingathome (LinuxServer.io)
    ca_ES: Foldingathome (LinuxServer.io)
    cs_CZ: Foldingathome (LinuxServer.io)
    da_DK: Foldingathome (LinuxServer.io)
    de_DE: Foldingathome (LinuxServer.io)
    el_GR: Foldingathome (LinuxServer.io)
    en_GB: Foldingathome (LinuxServer.io)
    es_ES: Foldingathome (LinuxServer.io)
    fr_FR: Foldingathome (LinuxServer.io)
    ga_IE: Foldingathome (LinuxServer.io)
    hr_HR: Foldingathome (LinuxServer.io)
    hu_HU: Foldingathome (LinuxServer.io)
    it_IT: Foldingathome (LinuxServer.io)
    ja_JP: Foldingathome (LinuxServer.io)
    ko_KR: Foldingathome (LinuxServer.io)
    ml_IN: Foldingathome (LinuxServer.io)
    nb_NO: Foldingathome (LinuxServer.io)
    nl_NL: Foldingathome (LinuxServer.io)
    pl_PL: Foldingathome (LinuxServer.io)
    pt_BR: Foldingathome (LinuxServer.io)
    ro_RO: Foldingathome (LinuxServer.io)
    ru_RU: Foldingathome (LinuxServer.io)
    sk_SK: Foldingathome (LinuxServer.io)
    sv_SE: Foldingathome (LinuxServer.io)
    tr_TR: Foldingathome (LinuxServer.io)
    zh_CN: Foldingathome（LinuxServer.io）
    zh_TW: Foldingathome（LinuxServer.io）
  id: by-roket.linuxserver.foldingathome
  port_map: '80'
  version: 8.5.6
  index: /
