name: linuxserver-foldingathome
services:
  foldingathome:
    image: linuxserver/foldingathome:8.5.6@sha256:a17f19c93a0a96bc8164017661c851d1e3d6b9f4c67b0fe244c8ff6407676b64
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ACCOUNT_TOKEN: ''
      MACHINE_NAME: ''
      CLI_ARGS: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 7396
        published: 7396
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: foldingathome-by-roket
x-casaos:
  main: foldingathome
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.foldingathome/assets/icon.png
  title:
    en_US: Foldingathome (LinuxServer.io)
  id: by-roket.linuxserver.foldingathome
  port_map: '80'
  version: 8.5.6
  index: /
