name: linuxserver-webcord
services:
  webcord:
    image: linuxserver/webcord:4.14.0@sha256:c76d5eead5dc6b61f90df5790780519bd9b8f87fa3bc5abb0f33c61e861ce18a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: webcord-by-roket
x-casaos:
  main: webcord
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.webcord/assets/icon.png
  title:
    en_US: Webcord (LinuxServer.io)
  id: by-roket.linuxserver.webcord
  port_map: '3000'
  version: 4.14.0
  index: /
