name: linuxserver-webcord
services:
  webcord:
    image: linuxserver/webcord:4.14.0@sha256:c76d5eead5dc6b61f90df5790780519bd9b8f87fa3bc5abb0f33c61e861ce18a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: webcord-by-roket
x-casaos:
  main: webcord
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.webcord/assets/icon.png
  title:
    en_US: Webcord (LinuxServer.io)
    ca_ES: Webcord (LinuxServer.io)
    cs_CZ: Webcord (LinuxServer.io)
    da_DK: Webcord (LinuxServer.io)
    de_DE: Webcord (LinuxServer.io)
    el_GR: Webcord (LinuxServer.io)
    en_GB: Webcord (LinuxServer.io)
    es_ES: Webcord (LinuxServer.io)
    fr_FR: Webcord (LinuxServer.io)
    ga_IE: Webcord (LinuxServer.io)
    hr_HR: Webcord (LinuxServer.io)
    hu_HU: Webcord (LinuxServer.io)
    it_IT: Webcord (LinuxServer.io)
    ja_JP: Webcord (LinuxServer.io)
    ko_KR: Webcord (LinuxServer.io)
    ml_IN: Webcord (LinuxServer.io)
    nb_NO: Webcord (LinuxServer.io)
    nl_NL: Webcord (LinuxServer.io)
    pl_PL: Webcord (LinuxServer.io)
    pt_BR: Webcord (LinuxServer.io)
    ro_RO: Webcord (LinuxServer.io)
    ru_RU: Webcord (LinuxServer.io)
    sk_SK: Webcord (LinuxServer.io)
    sv_SE: Webcord (LinuxServer.io)
    tr_TR: Webcord (LinuxServer.io)
    zh_CN: Webcord（LinuxServer.io）
    zh_TW: Webcord（LinuxServer.io）
  id: by-roket.linuxserver.webcord
  port_map: '3000'
  version: 4.14.0
  index: /
