name: linuxserver-raneto
services:
  raneto:
    image: linuxserver/raneto:0.18.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/raneto/config
        target: /config
x-casaos:
  main: raneto
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.raneto/assets/icon.png
  title:
    en_US: Raneto
  port_map: '3000'
  id: by-roket.linuxserver.raneto
  version: 0.18.1
  index: /
