name: linuxserver-intellij-idea
services:
  intellij-idea:
    image: linuxserver/intellij-idea:42026.2.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: intellij-idea-by-roket
x-casaos:
  main: intellij-idea
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.intellij-idea/assets/icon.png
  title:
    en_US: Intellij idea (LinuxServer.io)
  id: by-roket.linuxserver.intellij-idea
  port_map: '3000'
  version: 42026.2.0
  index: /
