name: linuxserver-bambustudio
services:
  bambustudio:
    image: linuxserver/bambustudio:02.08.02@sha256:f9f74e853333c975ca4ec3503c12bc1961b8261d143e44e08d1e58e5ac2969c4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DARK_MODE: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: bambustudio-by-roket
x-casaos:
  main: bambustudio
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.bambustudio/assets/icon.png
  title:
    en_US: Bambustudio (LinuxServer.io)
  id: by-roket.linuxserver.bambustudio
  port_map: '3000'
  version: 02.08.02
  index: /
