name: linuxserver-bambustudio
services:
  app:
    image: linuxserver/bambustudio:02.08.02
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DARK_MODE: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bambustudio/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.bambustudio/assets/icon.png
  title:
    en_US: Bambustudio
  port_map: '3000'
  id: by-roket.linuxserver.bambustudio
  version: 02.08.02
  index: /
