name: linuxserver-freshrss
services:
  freshrss:
    image: linuxserver/freshrss:1.29.1@sha256:e5ab19ccff35c69d5dfda0c2422a2d1e2b0a97722927982f13f538d0fca00dbb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: freshrss-by-roket
x-casaos:
  main: freshrss
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.freshrss/assets/icon.png
  title:
    en_US: Freshrss (LinuxServer.io)
  id: by-roket.linuxserver.freshrss
  port_map: '80'
  version: 1.29.1
  index: /
