name: linuxserver-sealskin
services:
  sealskin:
    image: linuxserver/sealskin:0.1.39@sha256:a016e8696f6f06d3ef2c5896692fd230f34e8d85d324a97b90dd5e8ec74a00f4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HOST_URL: ''
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sealskin/config
        target: /config
      - type: bind
        source: /DATA/AppData/sealskin/storage
        target: /storage
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  main: sealskin
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.sealskin/assets/icon.png
  title:
    en_US: Sealskin
  port_map: '8000'
  id: by-roket.linuxserver.sealskin
  version: 0.1.39
  index: /
