name: linuxserver-altus
services:
  altus:
    image: linuxserver/altus:5.8.1@sha256:c7393de970730025193557ea689c9f6e70a77e15728ea36e88bf7e5e023a1e23
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: altus-by-roket
x-casaos:
  main: altus
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.altus/assets/icon.png
  title:
    en_US: Altus (LinuxServer.io)
  id: by-roket.linuxserver.altus
  port_map: '3000'
  version: 5.8.1
  index: /
