name: linuxserver-ungoogled-chromium
services:
  ungoogled-chromium:
    image: linuxserver/ungoogled-chromium:152.0.7977@sha256:897f46fdc74de39bc6a93862b801dd2ca82ae373291ac9b0202910a954cdf07d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: ungoogled-chromium-by-roket
x-casaos:
  main: ungoogled-chromium
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ungoogled-chromium/assets/icon.png
  title:
    en_US: Ungoogled chromium (LinuxServer.io)
  id: by-roket.linuxserver.ungoogled-chromium
  port_map: '3000'
  version: 152.0.7977
  index: /
