name: linuxserver-helium
services:
  app:
    image: linuxserver/helium:0.15.6@sha256:12a8b546c49eb18880cc23de1778b71443aeba0b52e1ddde8ed0682cfc2296dc
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HELIUM_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/helium/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.helium/assets/icon.png
  title:
    en_US: Helium
  port_map: '3000'
  id: by-roket.linuxserver.helium
  version: 0.15.6
  index: /
