name: linuxserver-helium
services:
  helium:
    image: linuxserver/helium:0.15.7@sha256:eba711a8f6e632b4996bc5b5e79072b126d99049ee62ed34947ca6cc3c2cd617
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HELIUM_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: helium-by-roket
x-casaos:
  main: helium
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.helium/assets/icon.png
  title:
    en_US: Helium
  port_map: '3000'
  id: by-roket.linuxserver.helium
  version: 0.15.7
  index: /
