name: linuxserver-helium
services:
  helium:
    image: linuxserver/helium:0.16.6@sha256:084c90f6168cf4d9f8cbb42db24cacdaf9f548552774c5c0059fa48d8e986f2f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HELIUM_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: helium-by-roket
x-casaos:
  main: helium
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.helium/assets/icon.png
  title:
    en_US: Helium (LinuxServer.io)
  id: by-roket.linuxserver.helium
  port_map: '3000'
  version: 0.16.6
  index: /
