name: linuxserver-minisatip
services:
  minisatip:
    image: linuxserver/minisatip:2.0.100
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RUN_OPTS: ''
    ports:
      - target: 8875
        published: 8875
        protocol: tcp
      - target: 554
        published: 554
        protocol: tcp
      - target: 1900
        published: 1900
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: minisatip-by-roket
x-casaos:
  main: minisatip
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.minisatip/assets/icon.png
  title:
    en_US: Minisatip (LinuxServer.io)
  id: by-roket.linuxserver.minisatip
  version: 2.0.100
  index: /
  port_map: '8875'
