name: linuxserver-deluge
services:
  deluge:
    image: linuxserver/deluge:2.2.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DELUGE_LOGLEVEL: ''
    ports:
      - target: 8112
        published: 8112
        protocol: tcp
      - target: 6881
        published: 6881
        protocol: tcp
      - target: 6881
        published: 6881
        protocol: udp
      - target: 58846
        published: 58846
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: deluge-by-roket
x-casaos:
  main: deluge
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.deluge/assets/icon.png
  title:
    en_US: Deluge (LinuxServer.io)
  id: by-roket.linuxserver.deluge
  version: 2.2.0
  index: /
  port_map: '8112'
