name: linuxserver-grocy
services:
  grocy:
    image: linuxserver/grocy:4.7.0@sha256:deb07d373a21430de2bf0e41af591066d5c012072945a655478d2f1021b9b073
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 9283
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: grocy-by-roket
x-casaos:
  main: grocy
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.grocy/assets/icon.png
  title:
    en_US: Grocy (LinuxServer.io)
  id: by-roket.linuxserver.grocy
  port_map: '80'
  version: 4.7.0
  index: /
