name: linuxserver-nzbget
services:
  nzbget:
    image: linuxserver/nzbget:26.3.20260827@sha256:cec2d1bba820b9220c95fc252ff4c570688a12516caa1843060e08c376628031
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      NZBGET_USER: ''
      NZBGET_PASS: ''
    ports:
      - target: 6789
        published: 6789
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: nzbget-by-roket
x-casaos:
  main: nzbget
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.nzbget/assets/icon.png
  title:
    en_US: Nzbget
  port_map: '6789'
  id: by-roket.linuxserver.nzbget
  version: 26.3.20260827
  index: /
