name: linuxserver-nzbget
services:
  nzbget:
    image: linuxserver/nzbget:26.3.20260904@sha256:47ec378ab41b6f1b205a68d8d6dd52cd93925f6e13b55a9e3881d37f70ec4bbe
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      NZBGET_USER: ''
      NZBGET_PASS: ''
    ports:
      - target: 6789
        published: 6789
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: nzbget-by-roket
x-casaos:
  main: nzbget
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.nzbget/assets/icon.png
  title:
    en_US: Nzbget (LinuxServer.io)
  id: by-roket.linuxserver.nzbget
  port_map: '6789'
  version: 26.3.20260904
  index: /
