name: linuxserver-nzbget
services:
  nzbget:
    image: linuxserver/nzbget:26.3.20260827@sha256:1eb1911bf39a090fc8b0ecd34538dbf0c0ff11399abc0b5c32cd9b4884f6c68f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      NZBGET_USER: ''
      NZBGET_PASS: ''
    ports:
      - target: 6789
        published: 6789
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: nzbget-by-roket
x-casaos:
  main: nzbget
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.nzbget/assets/icon.png
  title:
    en_US: Nzbget (LinuxServer.io)
  id: by-roket.linuxserver.nzbget
  port_map: '6789'
  version: 26.3.20260827
  index: /
