name: linuxserver-pidgin
services:
  pidgin:
    image: linuxserver/pidgin:2.14.14@sha256:5108dbce3c538b4df6ea830db6af3c590400df0b8d4fdaad4c2d925cb32be21b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pidgin/config
        target: /config
x-casaos:
  main: pidgin
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.pidgin/assets/icon.png
  title:
    en_US: Pidgin
  port_map: '3000'
  id: by-roket.linuxserver.pidgin
  version: 2.14.14
  index: /
