name: linuxserver-openshot
services:
  openshot:
    image: linuxserver/openshot:4.0.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: openshot-by-roket
x-casaos:
  main: openshot
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.openshot/assets/icon.png
  title:
    en_US: Openshot (LinuxServer.io)
  id: by-roket.linuxserver.openshot
  port_map: '3000'
  version: 4.0.0
  index: /
