name: linuxserver-openshot
services:
  openshot:
    image: linuxserver/openshot:3.5.1@sha256:0a9f0806a28cefcaffaa04122398f20a5a2275953cddbcc9900fde04b478d5e7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: openshot-by-roket
x-casaos:
  main: openshot
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.openshot/assets/icon.png
  title:
    en_US: Openshot
  port_map: '3000'
  id: by-roket.linuxserver.openshot
  version: 3.5.1
  index: /
