name: linuxserver-xemu
services:
  xemu:
    image: linuxserver/xemu:0.8.134@sha256:02c356b1f67d1094e4dab981bbc8bd700e97a6fa0d1c99b1e1334721a65392c8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/xemu/config
        target: /config
x-casaos:
  main: xemu
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.xemu/assets/icon.png
  title:
    en_US: Xemu
  port_map: '3000'
  id: by-roket.linuxserver.xemu
  version: 0.8.134
  index: /
