name: linuxserver-xemu
services:
  xemu:
    image: linuxserver/xemu:0.8.134@sha256:aac63ce5ad98e986716bbde50a69479fd71f9964891befae54bf9dc93716cd0a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: xemu-by-roket
x-casaos:
  main: xemu
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.xemu/assets/icon.png
  title:
    en_US: Xemu (LinuxServer.io)
  id: by-roket.linuxserver.xemu
  port_map: '3000'
  version: 0.8.134
  index: /
