name: linuxserver-dokuwiki
services:
  dokuwiki:
    image: linuxserver/dokuwiki:version-2026-07-14c@sha256:1e4037f1f104a7946a97ff61d852bef003a7ca7aa55dd5dc0e9e827253f79c0f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: dokuwiki-by-roket
x-casaos:
  main: dokuwiki
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.dokuwiki/assets/icon.png
  title:
    en_US: Dokuwiki (LinuxServer.io)
  id: by-roket.linuxserver.dokuwiki
  port_map: '80'
  version: version-2026-07-14c
  index: /
