name: linuxserver-ldap-auth
services:
  app:
    image: linuxserver/ldap-auth:3.4.7@sha256:413dc5fcf7f2017df182633c4bb3fe9317f1d8b9b7c3f78c012a02402866b21b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ldap-auth/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ldap-auth/assets/icon.png
  title:
    en_US: Ldap auth
  id: by-roket.linuxserver.ldap-auth
  version: 3.4.7
  index: /
  port_map: '8888'
