name: linuxserver-faster-whisper
services:
  faster-whisper:
    image: linuxserver/faster-whisper:3.6.0@sha256:4b0cd541a7627724640f58524053dfc752bc3aeaf759ea14a153b9699cd44be3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DEBUG: ''
      LOCAL_ONLY: ''
      WHISPER_BEAM: ''
      WHISPER_LANG: ''
      WHISPER_MODEL: ''
    ports:
      - target: 10300
        published: 10300
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: faster-whisper-by-roket
x-casaos:
  main: faster-whisper
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.faster-whisper/assets/icon.png
  title:
    en_US: Faster whisper (LinuxServer.io)
  id: by-roket.linuxserver.faster-whisper
  port_map: '10300'
  version: 3.6.0
  index: /
