name: linuxserver-vscode
services:
  vscode:
    image: linuxserver/vscode:1.135.0@sha256:fd04fd20f36da748aaac25ab4c0025bb0d3f87a6d2d6c0547c9be7548767befe
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: vscode-by-roket
x-casaos:
  main: vscode
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.vscode/assets/icon.png
  title:
    en_US: Vscode (LinuxServer.io)
  id: by-roket.linuxserver.vscode
  port_map: '3000'
  version: 1.135.0
  index: /
