name: linuxserver-inkscape
services:
  inkscape:
    image: linuxserver/inkscape:1.4.2@sha256:de43cf7c3e7cc68e313a5ea36de170b6dde4fbc0f6b71ac42692ee48eb625fd9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: inkscape-by-roket
x-casaos:
  main: inkscape
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.inkscape/assets/icon.png
  title:
    en_US: Inkscape
  port_map: '3000'
  id: by-roket.linuxserver.inkscape
  version: 1.4.2
  index: /
