name: linuxserver-booksonic-air
services:
  booksonic-air:
    image: linuxserver/booksonic-air:2201.1.0@sha256:f6c2ce4cbb040de8d09c4dbed7740e186e6e0e604e19f201685f7352d9a15bb6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONTEXT_PATH: ''
    ports:
      - target: 4040
        published: 4040
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/audiobooks
        target: /audiobooks
      - type: bind
        source: /DATA/AppData/$AppID/podcasts
        target: /podcasts
      - type: bind
        source: /DATA/AppData/$AppID/othermedia
        target: /othermedia
    container_name: booksonic-air-by-roket
x-casaos:
  main: booksonic-air
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.booksonic-air/assets/icon.png
  title:
    en_US: Booksonic air
  port_map: '4040'
  id: by-roket.linuxserver.booksonic-air
  version: 2201.1.0
  index: /
