name: linuxserver-opera
services:
  app:
    image: linuxserver/opera:135.0.5973@sha256:77aab92a9f8d7aee1f9b10de04d8db3c7d004bd649a92cc1ee03b8d111c7dd75
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      OPERA_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/opera/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.opera/assets/icon.png
  title:
    en_US: Opera
  port_map: '3000'
  id: by-roket.linuxserver.opera
  version: 135.0.5973
  index: /
