name: linuxserver-hedgedoc
services:
  app:
    image: linuxserver/hedgedoc:1.12.0@sha256:91112de7cf589ffb193cdaae18b7886763c7acd7f3fca2938c3463e8500ffbf4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_HOST: ''
      DB_PORT: ''
      DB_USER: ''
      DB_PASS: ''
      DB_NAME: ''
      CMD_DOMAIN: ''
      CMD_URL_ADDPORT: ''
      CMD_PROTOCOL_USESSL: ''
      CMD_PORT: ''
      CMD_ALLOW_ORIGIN: ''
      CMD_DB_DIALECT: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/hedgedoc/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.hedgedoc/assets/icon.png
  title:
    en_US: Hedgedoc
  port_map: '3000'
  id: by-roket.linuxserver.hedgedoc
  version: 1.12.0
  index: /
