name: linuxserver-radarr
services:
  radarr:
    image: linuxserver/radarr:6.3.0@sha256:999a4ce9ef22927460161468a9c15c365dabe8d79eb380a2165f02e90dda4e79
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 7878
        published: 7878
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/movies
        target: /movies
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: radarr-by-roket
x-casaos:
  main: radarr
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.radarr/assets/icon.png
  title:
    en_US: Radarr (LinuxServer.io)
  id: by-roket.linuxserver.radarr
  port_map: '7878'
  version: 6.3.0
  index: /
