name: linuxserver-webstation
services:
  webstation:
    image: linuxserver/webstation:0.6.0-romm@sha256:40b094cdc311443004369dfd6ed1d7b28ab9378c8dcd97cae8da94f44c29a4ea
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: webstation-by-roket
x-casaos:
  main: webstation
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.webstation/assets/icon.png
  title:
    en_US: Webstation (LinuxServer.io)
  id: by-roket.linuxserver.webstation
  port_map: '3000'
  version: 0.6.0-romm
  index: /
