name: linuxserver-webstation
services:
  webstation:
    image: linuxserver/webstation:version-348c1bd6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: webstation-by-roket
x-casaos:
  main: webstation
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.webstation/assets/icon.png
  title:
    en_US: Webstation
  port_map: '3000'
  id: by-roket.linuxserver.webstation
  version: version-348c1bd6
  index: /
