name: linuxserver-rustdesk
services:
  app:
    image: linuxserver/rustdesk:1.4.9@sha256:38f8983f44d0a9c49d43ddcfd6459ee7ca5885d778050d654b0acc3a4072b7df
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rustdesk/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rustdesk/assets/icon.png
  title:
    en_US: Rustdesk
  port_map: '3000'
  id: by-roket.linuxserver.rustdesk
  version: 1.4.9
  index: /
