name: linuxserver-nzbhydra2
services:
  nzbhydra2:
    image: linuxserver/nzbhydra2:8.9.0@sha256:339100e76cd467f6ecd4c9bea5452c0f33bc48797427dc19677d679aba97dd3d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 5076
        published: 5076
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: nzbhydra2-by-roket
x-casaos:
  main: nzbhydra2
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.nzbhydra2/assets/icon.png
  title:
    en_US: Nzbhydra2 (LinuxServer.io)
  id: by-roket.linuxserver.nzbhydra2
  port_map: '5076'
  version: 8.9.0
  index: /
