name: linuxserver-boinc
services:
  boinc:
    image: linuxserver/boinc:8.2.8@sha256:e1a184a6f83923365fbe2c94af6b07470989b8827229eb2524532992cc00dec7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: boinc-by-roket
x-casaos:
  main: boinc
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.boinc/assets/icon.jpg
  title:
    en_US: Boinc (LinuxServer.io)
    ca_ES: Boinc (LinuxServer.io)
    cs_CZ: Boinc (LinuxServer.io)
    da_DK: Boinc (LinuxServer.io)
    de_DE: Boinc (LinuxServer.io)
    el_GR: Boinc (LinuxServer.io)
    en_GB: Boinc (LinuxServer.io)
    es_ES: Boinc (LinuxServer.io)
    fr_FR: Boinc (LinuxServer.io)
    ga_IE: Boinc (LinuxServer.io)
    hr_HR: Boinc (LinuxServer.io)
    hu_HU: Boinc (LinuxServer.io)
    it_IT: Boinc (LinuxServer.io)
    ja_JP: Boinc (LinuxServer.io)
    ko_KR: Boinc (LinuxServer.io)
    ml_IN: Boinc (LinuxServer.io)
    nb_NO: Boinc (LinuxServer.io)
    nl_NL: Boinc (LinuxServer.io)
    pl_PL: Boinc (LinuxServer.io)
    pt_BR: Boinc (LinuxServer.io)
    ro_RO: Boinc (LinuxServer.io)
    ru_RU: Boinc (LinuxServer.io)
    sk_SK: Boinc (LinuxServer.io)
    sv_SE: Boinc (LinuxServer.io)
    tr_TR: Boinc (LinuxServer.io)
    zh_CN: Boinc（LinuxServer.io）
    zh_TW: Boinc（LinuxServer.io）
  id: by-roket.linuxserver.boinc
  port_map: '8080'
  version: 8.2.8
  index: /
