name: linuxserver-digikam
services:
  digikam:
    image: linuxserver/digikam:9.1.0@sha256:210922dcebfd56976cb9984cfb2e1882faf9a1837b007acf3e173e44ee97a8d6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: digikam-by-roket
x-casaos:
  main: digikam
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.digikam/assets/icon.png
  title:
    en_US: Digikam (LinuxServer.io)
  id: by-roket.linuxserver.digikam
  port_map: '3000'
  version: 9.1.0
  index: /
