name: linuxserver-digikam
services:
  app:
    image: linuxserver/digikam:9.1.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/digikam/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.digikam/assets/icon.png
  title:
    en_US: Digikam
  port_map: '3000'
  id: by-roket.linuxserver.digikam
  version: 9.1.0
  index: /
