name: linuxserver-medusa
services:
  medusa:
    image: linuxserver/medusa:1.0.26@sha256:eb8a8df393ba46a453671af513681716a41e8b3dabe6c67581f31ea0b457c1d0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/$AppID/tv
        target: /tv
    container_name: medusa-by-roket
x-casaos:
  main: medusa
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.medusa/assets/icon.png
  title:
    en_US: Medusa (LinuxServer.io)
  id: by-roket.linuxserver.medusa
  port_map: '8081'
  version: 1.0.26
  index: /
