name: linuxserver-libreoffice
services:
  app:
    image: linuxserver/libreoffice:25.8.7@sha256:ff5c319ce5c46971c1be6fd1a1694f351508fa11f58111433caec662c00ece21
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/libreoffice/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.libreoffice/assets/icon.png
  title:
    en_US: Libreoffice
  port_map: '3000'
  id: by-roket.linuxserver.libreoffice
  version: 25.8.7
  index: /
