name: linuxserver-rpcs3
services:
  rpcs3:
    image: linuxserver/rpcs3:version-build-7be182e33bfa92a22d01bfb1b9c4188eff1165d5@sha256:fd585560d9a8e561b5a72088e69637924665ad771c61ba2f6f3e168acbcc4bd1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: rpcs3-by-roket
x-casaos:
  main: rpcs3
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rpcs3/assets/icon.png
  title:
    en_US: Rpcs3 (LinuxServer.io)
  id: by-roket.linuxserver.rpcs3
  port_map: '3000'
  version: version-build-7be182e33bfa92a22d01bfb1b9c4188eff1165d5
  index: /
