name: linuxserver-rpcs3
services:
  rpcs3:
    image: linuxserver/rpcs3:version-build-0514f521e9578489778294c848f5f32d6f0d670c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: rpcs3-by-roket
x-casaos:
  main: rpcs3
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rpcs3/assets/icon.png
  title:
    en_US: Rpcs3 (LinuxServer.io)
  id: by-roket.linuxserver.rpcs3
  port_map: '3000'
  version: version-build-0514f521e9578489778294c848f5f32d6f0d670c
  index: /
