name: linuxserver-rpcs3
services:
  rpcs3:
    image: linuxserver/rpcs3:version-build-0c0614a4df4bcc4e68e17ac9ba555f10f1d9645a@sha256:95a23b217f9b0f3068936e481f1f4fb69480ea75a3ced7ef318a2a449e0a132f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: rpcs3-by-roket
x-casaos:
  main: rpcs3
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rpcs3/assets/icon.png
  title:
    en_US: Rpcs3 (LinuxServer.io)
  id: by-roket.linuxserver.rpcs3
  port_map: '3000'
  version: version-build-0c0614a4df4bcc4e68e17ac9ba555f10f1d9645a
  index: /
