name: linuxserver-rpcs3
services:
  rpcs3:
    image: linuxserver/rpcs3:version-build-f2ac83f5eb0d3b34928438f7911aabcb9c14bd3b@sha256:6859859b8a9285e2e755d8ae61fab161e6c5d85f9bf37b82f3f8b88cf12a40ad
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: rpcs3-by-roket
x-casaos:
  main: rpcs3
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rpcs3/assets/icon.png
  title:
    en_US: Rpcs3 (LinuxServer.io)
  id: by-roket.linuxserver.rpcs3
  port_map: '3000'
  version: version-build-f2ac83f5eb0d3b34928438f7911aabcb9c14bd3b
  index: /
