name: linuxserver-rpcs3
services:
  rpcs3:
    image: linuxserver/rpcs3:version-build-275c2d40931c2bb40d75a29d8d299791c293d497@sha256:052a51db431cda0593c2a238647cc97f4b148d9ac05b558e17dc79f688d6d74e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: rpcs3-by-roket
x-casaos:
  main: rpcs3
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rpcs3/assets/icon.png
  title:
    en_US: Rpcs3 (LinuxServer.io)
  id: by-roket.linuxserver.rpcs3
  port_map: '3000'
  version: version-build-275c2d40931c2bb40d75a29d8d299791c293d497
  index: /
