name: linuxserver-rpcs3
services:
  rpcs3:
    image: linuxserver/rpcs3:version-build-2416d652625eaed5df2ff8d67063fa145021a883@sha256:bb0ee2b4ca1cbe6f80672f5cf99abaa3f0674fb4369e73ce90e19f2914879f5f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: rpcs3-by-roket
x-casaos:
  main: rpcs3
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rpcs3/assets/icon.png
  title:
    en_US: Rpcs3
  port_map: '3000'
  id: by-roket.linuxserver.rpcs3
  version: version-build-2416d652625eaed5df2ff8d67063fa145021a883
  index: /
