name: linuxserver-orcaslicer
services:
  orcaslicer:
    image: linuxserver/orcaslicer:2.4.2@sha256:be7d6c9033d5652d0bb8eafd54ee80f6a56362ea8a61b11c123b16d78d8af78d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: orcaslicer-by-roket
x-casaos:
  main: orcaslicer
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.orcaslicer/assets/icon.png
  title:
    en_US: Orcaslicer (LinuxServer.io)
  id: by-roket.linuxserver.orcaslicer
  port_map: '3000'
  version: 2.4.2
  index: /
