name: linuxserver-shadps4
services:
  shadps4:
    image: linuxserver/shadps4:version-shadPS4QtLauncher-2026-08-18-a30486c3e0a17460c44cf1caf15559c6f3331e57@sha256:5a1001dc18f727e7d77216e1510699ded9bfa4d677057da81058136fc920ac2c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/shadps4/config
        target: /config
x-casaos:
  main: shadps4
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.shadps4/assets/icon.png
  title:
    en_US: Shadps4
  port_map: '3000'
  id: by-roket.linuxserver.shadps4
  version: version-shadPS4QtLauncher-2026-08-18-a30486c3e0a17460c44cf1caf15559c6f3331e57
  index: /
