name: linuxserver-shadps4
services:
  shadps4:
    image: linuxserver/shadps4:version-shadPS4QtLauncher-2026-09-01-bf2c711d3e508671fe9b6b417355defff1fb6237@sha256:ddbc6ace264e8ae2b82d059fb51d09553bf5be52eb195c73520c36dae24cef12
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: shadps4-by-roket
x-casaos:
  main: shadps4
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.shadps4/assets/icon.png
  title:
    en_US: Shadps4 (LinuxServer.io)
  id: by-roket.linuxserver.shadps4
  port_map: '3000'
  version: version-shadPS4QtLauncher-2026-09-01-bf2c711d3e508671fe9b6b417355defff1fb6237
  index: /
