name: linuxserver-phpmyadmin
services:
  phpmyadmin:
    image: linuxserver/phpmyadmin:5.2.3@sha256:a809f05b8e6e994f12c7a5fdbd4afb5625dabefeb6b1de4b5eb51b679c639449
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PMA_ARBITRARY: ''
      PMA_ABSOLUTE_URI: ''
      PMA_HOST: 172.17.0.1
      PMA_USER: casaos
      PMA_PASSWORD: casaos
    ports:
      - target: 8081
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: phpmyadmin-by-roket
x-casaos:
  main: phpmyadmin
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.phpmyadmin/assets/icon.png
  title:
    en_US: Phpmyadmin (LinuxServer.io)
  id: by-roket.linuxserver.phpmyadmin
  port_map: '8081'
  version: 5.2.3
  index: /
