name: linuxserver-steam
services:
  steam:
    image: linuxserver/steam:version-9c3e4a41@sha256:3b98f7933bcf13d784ff06924c75ffd773a3fcfdb7d9f40cd5c7c005e3776a62
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: steam-by-roket
x-casaos:
  main: steam
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.steam/assets/icon.png
  title:
    en_US: Steam
  port_map: '3000'
  id: by-roket.linuxserver.steam
  version: version-9c3e4a41
  index: /
