name: linuxserver-piwigo
services:
  app:
    image: linuxserver/piwigo:16.4.0@sha256:0fd537a8ac591e49dea44c024795abfa8c4e7899cca2fca712ccdc7a69c87f7f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/piwigo/config
        target: /config
      - type: bind
        source: /DATA/AppData/piwigo/gallery
        target: /gallery
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.piwigo/assets/icon.png
  title:
    en_US: Piwigo
  port_map: '80'
  id: by-roket.linuxserver.piwigo
  version: 16.4.0
  index: /
