name: linuxserver-filezilla
services:
  filezilla:
    image: linuxserver/filezilla:3.69.6@sha256:324b54917154c67af8fc1b2308ff4a1933db65398dfdf61d9fc3cfd89383dfd8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: filezilla-by-roket
x-casaos:
  main: filezilla
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.filezilla/assets/icon.png
  title:
    en_US: Filezilla (LinuxServer.io)
  id: by-roket.linuxserver.filezilla
  port_map: '3000'
  version: 3.69.6
  index: /
