name: linuxserver-filezilla
services:
  filezilla:
    image: linuxserver/filezilla:3.69.6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: filezilla-by-roket
x-casaos:
  main: filezilla
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.filezilla/assets/icon.png
  title:
    en_US: Filezilla (LinuxServer.io)
    ca_ES: Filezilla (LinuxServer.io)
    cs_CZ: Filezilla (LinuxServer.io)
    da_DK: Filezilla (LinuxServer.io)
    de_DE: Filezilla (LinuxServer.io)
    el_GR: Filezilla (LinuxServer.io)
    en_GB: Filezilla (LinuxServer.io)
    es_ES: Filezilla (LinuxServer.io)
    fr_FR: Filezilla (LinuxServer.io)
    ga_IE: Filezilla (LinuxServer.io)
    hr_HR: Filezilla (LinuxServer.io)
    hu_HU: Filezilla (LinuxServer.io)
    it_IT: Filezilla (LinuxServer.io)
    ja_JP: Filezilla (LinuxServer.io)
    ko_KR: Filezilla (LinuxServer.io)
    ml_IN: Filezilla (LinuxServer.io)
    nb_NO: Filezilla (LinuxServer.io)
    nl_NL: Filezilla (LinuxServer.io)
    pl_PL: Filezilla (LinuxServer.io)
    pt_BR: Filezilla (LinuxServer.io)
    ro_RO: Filezilla (LinuxServer.io)
    ru_RU: Filezilla (LinuxServer.io)
    sk_SK: Filezilla (LinuxServer.io)
    sv_SE: Filezilla (LinuxServer.io)
    tr_TR: Filezilla (LinuxServer.io)
    zh_CN: Filezilla（LinuxServer.io）
    zh_TW: Filezilla（LinuxServer.io）
  id: by-roket.linuxserver.filezilla
  port_map: '3000'
  version: 3.69.6
  index: /
