name: linuxserver-d2-builder
services:
  d2-builder:
    image: linuxserver/d2-builder:0.6.8@sha256:ea8f88d0b1132234b87fec7a022b2f02b29d556576163639f7ee112044febf92
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: d2-builder-by-roket
x-casaos:
  main: d2-builder
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.d2-builder/assets/icon.png
  title:
    en_US: D2 builder
  port_map: '80'
  id: by-roket.linuxserver.d2-builder
  version: 0.6.8
  index: /
