name: linuxserver-flycast
services:
  flycast:
    image: linuxserver/flycast:2.7.20260819@sha256:ac5c04235b15784e926cc8dcb39496e6745283fea9d578754245ac5e0e5890ef
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/flycast/config
        target: /config
x-casaos:
  main: flycast
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.flycast/assets/icon.png
  title:
    en_US: Flycast
  port_map: '3000'
  id: by-roket.linuxserver.flycast
  version: 2.7.20260819
  index: /
