name: linuxserver-joplin
services:
  joplin:
    image: linuxserver/joplin:3.7.16@sha256:cb543b498ca7265d8b740d6749a4f2fb21c0d0183ed5d6c5ae6ea3fbe072ba9f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: joplin-by-roket
x-casaos:
  main: joplin
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.joplin/assets/icon.png
  title:
    en_US: Joplin (LinuxServer.io)
  id: by-roket.linuxserver.joplin
  port_map: '3000'
  version: 3.7.16
  index: /
