name: linuxserver-joplin
services:
  joplin:
    image: linuxserver/joplin:3.7.18
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: joplin-by-roket
x-casaos:
  main: joplin
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.joplin/assets/icon.png
  title:
    en_US: Joplin (LinuxServer.io)
    ca_ES: Joplin (LinuxServer.io)
    cs_CZ: Joplin (LinuxServer.io)
    da_DK: Joplin (LinuxServer.io)
    de_DE: Joplin (LinuxServer.io)
    el_GR: Joplin (LinuxServer.io)
    en_GB: Joplin (LinuxServer.io)
    es_ES: Joplin (LinuxServer.io)
    fr_FR: Joplin (LinuxServer.io)
    ga_IE: Joplin (LinuxServer.io)
    hr_HR: Joplin (LinuxServer.io)
    hu_HU: Joplin (LinuxServer.io)
    it_IT: Joplin (LinuxServer.io)
    ja_JP: Joplin (LinuxServer.io)
    ko_KR: Joplin (LinuxServer.io)
    ml_IN: Joplin (LinuxServer.io)
    nb_NO: Joplin (LinuxServer.io)
    nl_NL: Joplin (LinuxServer.io)
    pl_PL: Joplin (LinuxServer.io)
    pt_BR: Joplin (LinuxServer.io)
    ro_RO: Joplin (LinuxServer.io)
    ru_RU: Joplin (LinuxServer.io)
    sk_SK: Joplin (LinuxServer.io)
    sv_SE: Joplin (LinuxServer.io)
    tr_TR: Joplin (LinuxServer.io)
    zh_CN: Joplin（LinuxServer.io）
    zh_TW: Joplin（LinuxServer.io）
  id: by-roket.linuxserver.joplin
  port_map: '3000'
  version: 3.7.18
  index: /
