name: linuxserver-plex
services:
  plex:
    image: linuxserver/plex:1.43.3@sha256:94b8e5dc1797cd54d64da5a8df8b3391d698309185fecdc5e63deff5c95988dd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VERSION: ''
      PLEX_CLAIM: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/tv
        target: /tv
      - type: bind
        source: /DATA/AppData/$AppID/movies
        target: /movies
    container_name: plex-by-roket
x-casaos:
  main: plex
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.plex/assets/icon.png
  title:
    en_US: Plex
  port_map: '80'
  id: by-roket.linuxserver.plex
  version: 1.43.3
  index: /
