name: linuxserver-zen
services:
  zen:
    image: linuxserver/zen:1.21.15@sha256:942f3c3fd326455b768468055c8dd5f4a4e4940156b26c9f3fef6b5e40ac4bc1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/zen/config
        target: /config
x-casaos:
  main: zen
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.zen/assets/icon.png
  title:
    en_US: Zen
  port_map: '3000'
  id: by-roket.linuxserver.zen
  version: 1.21.15
  index: /
