name: linuxserver-zen
services:
  zen:
    image: linuxserver/zen:1.21.16@sha256:62fbe0c4282e57553637a4543e78d3e7be5fa20e6ef9e12b554b700874bfba6c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: zen-by-roket
x-casaos:
  main: zen
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.zen/assets/icon.png
  title:
    en_US: Zen (LinuxServer.io)
  id: by-roket.linuxserver.zen
  port_map: '3000'
  version: 1.21.16
  index: /
