name: linuxserver-handbrake
services:
  handbrake:
    image: linuxserver/handbrake:1.11.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: handbrake-by-roket
x-casaos:
  main: handbrake
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.handbrake/assets/icon.png
  title:
    en_US: Handbrake (LinuxServer.io)
  id: by-roket.linuxserver.handbrake
  port_map: '3000'
  version: 1.11.2
  index: /
