name: linuxserver-wireguard
services:
  wireguard:
    image: linuxserver/wireguard:1.0.20260223@sha256:fe60048c3096b8347aa4e483213ab75a670460abd24764c5407f699f23d3b46d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SERVERURL: ''
      SERVERPORT: ''
      PEERS: ''
      PEERDNS: ''
      INTERNAL_SUBNET: ''
      ALLOWEDIPS: ''
      PERSISTENTKEEPALIVE_PEERS: ''
      LOG_CONFS: ''
    ports:
      - target: 51820
        published: 51820
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /lib/modules
        target: /lib/modules
    container_name: wireguard-by-roket
x-casaos:
  main: wireguard
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.wireguard/assets/icon.svg
  title:
    en_US: Wireguard
  port_map: '51820'
  id: by-roket.linuxserver.wireguard
  version: 1.0.20260223
  index: /
