name: linuxserver-rawtherapee
services:
  rawtherapee:
    image: linuxserver/rawtherapee:5.13.20260816@sha256:17916a6eaee25131d2f7c42bd48cc1ed048c79b218e4163ef7f2f72da833d054
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rawtherapee/config
        target: /config
x-casaos:
  main: rawtherapee
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rawtherapee/assets/icon.png
  title:
    en_US: Rawtherapee
  port_map: '3000'
  id: by-roket.linuxserver.rawtherapee
  version: 5.13.20260816
  index: /
