name: linuxserver-rawtherapee
services:
  rawtherapee:
    image: linuxserver/rawtherapee:5.13.20260823@sha256:7892aeb58bc94513f07e4b5165a4d0cfff71666fa1caeafe7073a50d07db5a14
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: rawtherapee-by-roket
x-casaos:
  main: rawtherapee
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.rawtherapee/assets/icon.png
  title:
    en_US: Rawtherapee
  port_map: '3000'
  id: by-roket.linuxserver.rawtherapee
  version: 5.13.20260823
  index: /
