name: linuxserver-qdirstat
services:
  qdirstat:
    image: linuxserver/qdirstat:2.0.20260831
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: qdirstat-by-roket
x-casaos:
  main: qdirstat
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.qdirstat/assets/icon.png
  title:
    en_US: Qdirstat (LinuxServer.io)
  id: by-roket.linuxserver.qdirstat
  port_map: '3000'
  version: 2.0.20260831
  index: /
