name: linuxserver-doplarr_rs
services:
  doplarr_rs:
    image: linuxserver/doplarr_rs:4.6.0@sha256:6a2fecfeb7b5d97dedcb065852c96f2b8a5f43e53e9c2a509b21f577a3765bdc
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: doplarr_rs-by-roket
x-casaos:
  main: doplarr_rs
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.doplarr_rs/assets/icon.png
  title:
    en_US: Doplarr_rs
  port_map: '80'
  id: by-roket.linuxserver.doplarr_rs
  version: 4.6.0
  index: /
