name: linuxserver-kometa
services:
  kometa:
    image: linuxserver/kometa:2.4.8@sha256:957fff0ed3067c6df11fc9566b1ff7eefe6b98ee63ed7fc619954203214e510c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      KOMETA_CONFIG: ''
      KOMETA_TIMES: ''
      KOMETA_RUN: ''
      KOMETA_TESTS: ''
      KOMETA_NO_MISSING: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: kometa-by-roket
x-casaos:
  main: kometa
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.kometa/assets/icon.png
  title:
    en_US: Kometa
  port_map: '80'
  id: by-roket.linuxserver.kometa
  version: 2.4.8
  index: /
