name: linuxserver-kometa
services:
  kometa:
    image: linuxserver/kometa:2.4.8@sha256:1c0921413e16c6c31bf75a842a520543743a5786007016bd3db65956401702e4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      KOMETA_CONFIG: ''
      KOMETA_TIMES: ''
      KOMETA_RUN: ''
      KOMETA_TESTS: ''
      KOMETA_NO_MISSING: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: kometa-by-roket
x-casaos:
  main: kometa
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.kometa/assets/icon.png
  title:
    en_US: Kometa (LinuxServer.io)
  id: by-roket.linuxserver.kometa
  port_map: '80'
  version: 2.4.8
  index: /
