name: linuxserver-emby
services:
  emby:
    image: linuxserver/emby:4.9.5@sha256:80a27be46c1bc8357461314e25d541f8706c237a518971635ad56e787155aaf3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8096
        published: 8096
        protocol: tcp
      - target: 8920
        published: 8920
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data/tvshows
        target: /data/tvshows
      - type: bind
        source: /DATA/AppData/$AppID/data/movies
        target: /data/movies
      - type: bind
        source: /opt/vc/lib
        target: /opt/vc/lib
    container_name: emby-by-roket
x-casaos:
  main: emby
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.emby/assets/icon.png
  title:
    en_US: Emby
  id: by-roket.linuxserver.emby
  version: 4.9.5
  index: /
  port_map: '8096'
