name: linuxserver-mstream
services:
  mstream:
    image: linuxserver/mstream:6.24.0@sha256:5533f395a9af415d07fc9f1cde226abd5cf931f60514168f2bc701bf256178aa
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/music
        target: /music
    container_name: mstream-by-roket
x-casaos:
  main: mstream
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.mstream/assets/icon.png
  title:
    en_US: Mstream
  port_map: '3000'
  id: by-roket.linuxserver.mstream
  version: 6.24.0
  index: /
