name: linuxserver-mstream
services:
  mstream:
    image: linuxserver/mstream:6.25.0@sha256:9c96192b9dc31ce89cd02b10530556f5c761225dc95921234c42dbd191863c8f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/music
        target: /music
    container_name: mstream-by-roket
x-casaos:
  main: mstream
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.mstream/assets/icon.png
  title:
    en_US: Mstream (LinuxServer.io)
  id: by-roket.linuxserver.mstream
  port_map: '3000'
  version: 6.25.0
  index: /
