name: linuxserver-mstream
services:
  mstream:
    image: linuxserver/mstream:6.22.0@sha256:649101c30eed8b54c53475b1c3831c0286e359744613ac8ac926aaabed6e5c52
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/music
        target: /music
    container_name: mstream-by-roket
x-casaos:
  main: mstream
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.mstream/assets/icon.png
  title:
    en_US: Mstream
  port_map: '3000'
  id: by-roket.linuxserver.mstream
  version: 6.22.0
  index: /
