name: linuxserver-sonarr
services:
  sonarr:
    image: linuxserver/sonarr:4.0.19
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8989
        published: 8989
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sonarr/config
        target: /config
      - type: bind
        source: /DATA/AppData/sonarr/tv
        target: /tv
      - type: bind
        source: /DATA/AppData/sonarr/downloads
        target: /downloads
x-casaos:
  main: sonarr
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.sonarr/assets/icon.png
  title:
    en_US: Sonarr
  port_map: '8989'
  id: by-roket.linuxserver.sonarr
  version: 4.0.19
  index: /
