name: linuxserver-kdenlive
services:
  kdenlive:
    image: linuxserver/kdenlive:26.08.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: kdenlive-by-roket
x-casaos:
  main: kdenlive
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.kdenlive/assets/icon.png
  title:
    en_US: Kdenlive (LinuxServer.io)
  id: by-roket.linuxserver.kdenlive
  port_map: '3000'
  version: 26.08.0
  index: /
