name: linuxserver-fail2ban
services:
  fail2ban:
    image: linuxserver/fail2ban:1.1.0@sha256:ae5b876208ec2bc079ae74f28c6cb6405d3f8f33a834d61eb97fe751efdb839d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VERBOSITY: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/var/log:ro
        target: /var/log:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/airsonic:ro
        target: /remotelogs/airsonic:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/apache2:ro
        target: /remotelogs/apache2:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/authelia:ro
        target: /remotelogs/authelia:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/emby:ro
        target: /remotelogs/emby:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/filebrowser:ro
        target: /remotelogs/filebrowser:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/homeassistant:ro
        target: /remotelogs/homeassistant:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/lighttpd:ro
        target: /remotelogs/lighttpd:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/nextcloud:ro
        target: /remotelogs/nextcloud:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/nginx:ro
        target: /remotelogs/nginx:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/nzbget:ro
        target: /remotelogs/nzbget:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/overseerr:ro
        target: /remotelogs/overseerr:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/prowlarr:ro
        target: /remotelogs/prowlarr:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/radarr:ro
        target: /remotelogs/radarr:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/sabnzbd:ro
        target: /remotelogs/sabnzbd:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/sonarr:ro
        target: /remotelogs/sonarr:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/unificontroller:ro
        target: /remotelogs/unificontroller:ro
      - type: bind
        source: /DATA/AppData/$AppID/remotelogs/vaultwarden:ro
        target: /remotelogs/vaultwarden:ro
    container_name: fail2ban-by-roket
x-casaos:
  main: fail2ban
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.fail2ban/assets/icon.png
  title:
    en_US: Fail2ban
  port_map: '80'
  id: by-roket.linuxserver.fail2ban
  version: 1.1.0
  index: /
