name: linuxserver-blender
services:
  blender:
    image: linuxserver/blender:5.2.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: blender-by-roket
x-casaos:
  main: blender
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.blender/assets/icon.png
  title:
    en_US: Blender
  port_map: '3000'
  id: by-roket.linuxserver.blender
  version: 5.2.0
  index: /
