name: linuxserver-librespeed
services:
  librespeed:
    image: linuxserver/librespeed:6.2.1@sha256:9ba90c7c8da7d7fd0d24b1fa38cd7188cdb3a94d3b69110fc996be766dbdb071
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      CUSTOM_RESULTS: ''
      DB_TYPE: ''
      DB_NAME: ''
      DB_HOSTNAME: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_PORT: ''
      IPINFO_APIKEY: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: librespeed-by-roket
x-casaos:
  main: librespeed
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.librespeed/assets/icon.png
  title:
    en_US: Librespeed (LinuxServer.io)
  id: by-roket.linuxserver.librespeed
  port_map: '80'
  version: 6.2.1
  index: /
