name: linuxserver-sickgear
services:
  sickgear:
    image: linuxserver/sickgear:3.36.2@sha256:e3a156d33601cc1ca4c858b44a2af4212f34481e3489c53558c60267d0731551
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/tv
        target: /tv
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: sickgear-by-roket
x-casaos:
  main: sickgear
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.sickgear/assets/icon.png
  title:
    en_US: Sickgear (LinuxServer.io)
  id: by-roket.linuxserver.sickgear
  port_map: '8081'
  version: 3.36.2
  index: /
