name: linuxserver-sickgear
services:
  app:
    image: linuxserver/sickgear:3.36.0@sha256:e0f676c067afe2f40e6e0332f9665786c6c918f018906fa148999ce9e657387a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sickgear/config
        target: /config
      - type: bind
        source: /DATA/AppData/sickgear/tv
        target: /tv
      - type: bind
        source: /DATA/AppData/sickgear/downloads
        target: /downloads
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.sickgear/assets/icon.png
  title:
    en_US: Sickgear
  port_map: '8081'
  id: by-roket.linuxserver.sickgear
  version: 3.36.0
  index: /
