name: linuxserver-dogwalk
services:
  dogwalk:
    image: linuxserver/dogwalk:cb661a4d-ls51@sha256:b58ed6333d6f6f4b9e8e015cd9663c4ae6023b01961006393c80dd8a87fcad70
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dogwalk/config
        target: /config
x-casaos:
  main: dogwalk
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.dogwalk/assets/icon.png
  title:
    en_US: Dogwalk
  port_map: '3000'
  id: by-roket.linuxserver.dogwalk
  version: cb661a4d-ls51
  index: /
