name: linuxserver-znc
services:
  znc:
    image: linuxserver/znc:1.10.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 6501
        published: 6501
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/znc/config
        target: /config
x-casaos:
  main: znc
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.znc/assets/icon.png
  title:
    en_US: Znc
  port_map: '6501'
  id: by-roket.linuxserver.znc
  version: 1.10.2
  index: /
