name: linuxserver-pelorus
services:
  pelorus:
    image: linuxserver/pelorus:0.2.3@sha256:557fc9d0309b194556ac09fdb840909f43e8f0db21508d01b4fb5c1741291cf9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: pelorus-by-roket
x-casaos:
  main: pelorus
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.pelorus/assets/icon.png
  title:
    en_US: Pelorus (LinuxServer.io)
  id: by-roket.linuxserver.pelorus
  port_map: '3001'
  version: 0.2.3
  index: /
