name: linuxserver-build-agent
services:
  build-agent:
    image: linuxserver/build-agent:version-0296acb5@sha256:5ea835919dd53e881c52e52bd158d631cb4c3beef15a10a150438539d63b98c8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/build-agent/config
        target: /config
x-casaos:
  main: build-agent
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.build-agent/assets/icon.png
  title:
    en_US: Build agent
  port_map: '80'
  id: by-roket.linuxserver.build-agent
  version: version-0296acb5
  index: /
