name: linuxserver-requestrr
services:
  requestrr:
    image: linuxserver/requestrr:2.1.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 4545
        published: 4545
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: requestrr-by-roket
x-casaos:
  main: requestrr
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.requestrr/assets/icon.png
  title:
    en_US: Requestrr
    zh_CN: Requestrr
    ca_ES: Requestrr
    cs_CZ: Requestrr
    da_DK: Requestrr
    de_DE: Requestrr
    el_GR: Requestrr
    en_GB: Requestrr
    es_ES: Requestrr
    fr_FR: Requestrr
    ga_IE: Requestrr
    hr_HR: Requestrr
    hu_HU: Requestrr
    it_IT: Requestrr
    ja_JP: Requestrr
    ko_KR: Requestrr
    ml_IN: Requestrr
    nb_NO: Requestrr
    nl_NL: Requestrr
    pl_PL: Requestrr
    pt_BR: Requestrr
    ro_RO: Requestrr
    ru_RU: Requestrr
    sk_SK: Requestrr
    sv_SE: Requestrr
    tr_TR: Requestrr
    zh_TW: Requestrr
  port_map: '4545'
  id: by-roket.linuxserver.requestrr
  version: 2.1.2
  index: /
