name: linuxserver-requestrr
services:
  requestrr:
    image: linuxserver/requestrr:2.1.2@sha256:a6fb3114d6194ed674baa70a7b8d61bc1dfe88a356ea3b74b835f9868287e633
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 4545
        published: 4545
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/requestrr/config
        target: /config
x-casaos:
  main: requestrr
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.requestrr/assets/icon.png
  title:
    en_US: Requestrr
  port_map: '4545'
  id: by-roket.linuxserver.requestrr
  version: 2.1.2
  index: /
