name: linuxserver-requestrr
services:
  requestrr:
    image: linuxserver/requestrr:2.1.2@sha256:416a163bc400e2d55115217397c69e759f0abeb4ce792b283756e0390de97d43
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 4545
        published: 4545
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/requestrr/config
        target: /config
x-casaos:
  main: requestrr
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.requestrr/assets/icon.png
  title:
    en_US: Requestrr
  port_map: '4545'
  id: by-roket.linuxserver.requestrr
  version: 2.1.2
  index: /
