name: linuxserver-pydio-cells
services:
  pydio-cells:
    image: linuxserver/pydio-cells:5.0.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EXTERNALURL: ''
      SERVER_IP: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: pydio-cells-by-roket
x-casaos:
  main: pydio-cells
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.pydio-cells/assets/icon.png
  title:
    en_US: Pydio cells (LinuxServer.io)
  id: by-roket.linuxserver.pydio-cells
  port_map: '8080'
  version: 5.0.2
  index: /
