name: linuxserver-librewolf
services:
  librewolf:
    image: linuxserver/librewolf:154.0.1@sha256:bb4051b0f2f5abf540dae358337e593280ec7f35c4ea969698dc6f605b103c5b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LIBREWOLF_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: librewolf-by-roket
x-casaos:
  main: librewolf
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.librewolf/assets/icon.png
  title:
    en_US: Librewolf
  port_map: '3000'
  id: by-roket.linuxserver.librewolf
  version: 154.0.1
  index: /
