name: linuxserver-pylon
services:
  pylon:
    image: linuxserver/pylon:2.10.0@sha256:be84d92b6c99659aeef60398763d240cd89927e6dda6f3d193573bb47bd367ae
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      GITURL: ''
      PYUSER: ''
      PYPASS: ''
    ports:
      - target: 3131
        published: 3131
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/code
        target: /code
    container_name: pylon-by-roket
x-casaos:
  main: pylon
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.pylon/assets/icon.png
  title:
    en_US: Pylon
  port_map: '3131'
  id: by-roket.linuxserver.pylon
  version: 2.10.0
  index: /
