name: linuxserver-readme-sync
services:
  readme-sync:
    image: linuxserver/readme-sync:84f2d0c3-ls27@sha256:24030eb9cbb824dd5334c5d9cee521049833514f9e12577c576fd28f1afd32a8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/readme-sync/config
        target: /config
x-casaos:
  main: readme-sync
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.readme-sync/assets/icon.png
  title:
    en_US: Readme sync
  port_map: '80'
  id: by-roket.linuxserver.readme-sync
  version: 84f2d0c3-ls27
  index: /
