name: linuxserver-bookstack
services:
  app:
    image: linuxserver/bookstack:26.05.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APP_URL: ''
      APP_KEY: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_DATABASE: ''
      QUEUE_CONNECTION: ''
    ports:
      - target: 6875
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bookstack/config
        target: /config
x-casaos:
  main: app
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.bookstack/assets/icon.png
  title:
    en_US: Bookstack
  port_map: '80'
  id: by-roket.linuxserver.bookstack
  version: 26.05.3
  index: /
