name: linuxserver-bookstack
services:
  bookstack:
    image: linuxserver/bookstack:26.05.4@sha256:fae99ddba6dc870d350eaa8151de1db92977b75f97950d2d1a2e2721e2763c3f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APP_URL: ''
      APP_KEY: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_DATABASE: ''
      QUEUE_CONNECTION: ''
    ports:
      - target: 6875
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: bookstack-by-roket
x-casaos:
  main: bookstack
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.bookstack/assets/icon.png
  title:
    en_US: Bookstack
  port_map: '80'
  id: by-roket.linuxserver.bookstack
  version: 26.05.4
  index: /
