name: linuxserver-projectsend
services:
  projectsend:
    image: linuxserver/projectsend:version-r2098
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: projectsend-by-roket
x-casaos:
  main: projectsend
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.projectsend/assets/icon.png
  title:
    en_US: Projectsend (LinuxServer.io)
    ca_ES: Projectsend (LinuxServer.io)
    cs_CZ: Projectsend (LinuxServer.io)
    da_DK: Projectsend (LinuxServer.io)
    de_DE: Projectsend (LinuxServer.io)
    el_GR: Projectsend (LinuxServer.io)
    en_GB: Projectsend (LinuxServer.io)
    es_ES: Projectsend (LinuxServer.io)
    fr_FR: Projectsend (LinuxServer.io)
    ga_IE: Projectsend (LinuxServer.io)
    hr_HR: Projectsend (LinuxServer.io)
    hu_HU: Projectsend (LinuxServer.io)
    it_IT: Projectsend (LinuxServer.io)
    ja_JP: Projectsend (LinuxServer.io)
    ko_KR: Projectsend (LinuxServer.io)
    ml_IN: Projectsend (LinuxServer.io)
    nb_NO: Projectsend (LinuxServer.io)
    nl_NL: Projectsend (LinuxServer.io)
    pl_PL: Projectsend (LinuxServer.io)
    pt_BR: Projectsend (LinuxServer.io)
    ro_RO: Projectsend (LinuxServer.io)
    ru_RU: Projectsend (LinuxServer.io)
    sk_SK: Projectsend (LinuxServer.io)
    sv_SE: Projectsend (LinuxServer.io)
    tr_TR: Projectsend (LinuxServer.io)
    zh_CN: Projectsend（LinuxServer.io）
    zh_TW: Projectsend（LinuxServer.io）
  id: by-roket.linuxserver.projectsend
  port_map: '80'
  version: version-r2098
  index: /
