name: linuxserver-projectsend
services:
  projectsend:
    image: linuxserver/projectsend:version-r2098
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: projectsend-by-roket
x-casaos:
  main: projectsend
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.projectsend/assets/icon.png
  title:
    en_US: Projectsend (LinuxServer.io)
  id: by-roket.linuxserver.projectsend
  port_map: '80'
  version: version-r2098
  index: /
