name: linuxserver-ubooquity
services:
  ubooquity:
    image: linuxserver/ubooquity:3.1.0@sha256:3d094ecde63404490c744cae328652cb49cbc695efb80d80bbf6cacc82855fcf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MAXMEM: ''
    ports:
      - target: 2202
        published: 2202
        protocol: tcp
      - target: 2203
        published: 2203
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/books
        target: /books
      - type: bind
        source: /DATA/AppData/$AppID/comics
        target: /comics
      - type: bind
        source: /DATA/AppData/$AppID/files
        target: /files
    container_name: ubooquity-by-roket
x-casaos:
  main: ubooquity
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ubooquity/assets/icon.png
  title:
    en_US: Ubooquity
  id: by-roket.linuxserver.ubooquity
  version: 3.1.0
  index: /
  port_map: '2202'
