name: linuxserver-signal
services:
  signal:
    image: linuxserver/signal:8.25.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: signal-by-roket
x-casaos:
  main: signal
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.signal/assets/icon.png
  title:
    en_US: Signal (LinuxServer.io)
  id: by-roket.linuxserver.signal
  port_map: '3000'
  version: 8.25.0
  index: /
