name: linuxserver-nntp2nntp
services:
  nntp2nntp:
    image: linuxserver/nntp2nntp:0.3.20230704@sha256:a435223dc52180b97b2977b5bb2b2fceb566ac45bb4b2d49d9eae7637924fa64
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 1563
        published: 1563
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: nntp2nntp-by-roket
x-casaos:
  main: nntp2nntp
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.nntp2nntp/assets/icon.png
  title:
    en_US: Nntp2nntp
  id: by-roket.linuxserver.nntp2nntp
  version: 0.3.20230704
  index: /
  port_map: '1563'
