name: linuxserver-keepassxc
services:
  keepassxc:
    image: linuxserver/keepassxc:2.7.12
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: keepassxc-by-roket
x-casaos:
  main: keepassxc
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.keepassxc/assets/icon.png
  title:
    en_US: Keepassxc (LinuxServer.io)
  id: by-roket.linuxserver.keepassxc
  port_map: '3000'
  version: 2.7.12
  index: /
