name: linuxserver-keepassxc
services:
  keepassxc:
    image: linuxserver/keepassxc:2.7.12@sha256:f5f39ba94a03fb614dd263758b85eb75799256a53b561ffa1059dd2a455988b2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: keepassxc-by-roket
x-casaos:
  main: keepassxc
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.keepassxc/assets/icon.png
  title:
    en_US: Keepassxc (LinuxServer.io)
    ca_ES: Keepassxc (LinuxServer.io)
    cs_CZ: Keepassxc (LinuxServer.io)
    da_DK: Keepassxc (LinuxServer.io)
    de_DE: Keepassxc (LinuxServer.io)
    el_GR: Keepassxc (LinuxServer.io)
    en_GB: Keepassxc (LinuxServer.io)
    es_ES: Keepassxc (LinuxServer.io)
    fr_FR: Keepassxc (LinuxServer.io)
    ga_IE: Keepassxc (LinuxServer.io)
    hr_HR: Keepassxc (LinuxServer.io)
    hu_HU: Keepassxc (LinuxServer.io)
    it_IT: Keepassxc (LinuxServer.io)
    ja_JP: Keepassxc (LinuxServer.io)
    ko_KR: Keepassxc (LinuxServer.io)
    ml_IN: Keepassxc (LinuxServer.io)
    nb_NO: Keepassxc (LinuxServer.io)
    nl_NL: Keepassxc (LinuxServer.io)
    pl_PL: Keepassxc (LinuxServer.io)
    pt_BR: Keepassxc (LinuxServer.io)
    ro_RO: Keepassxc (LinuxServer.io)
    ru_RU: Keepassxc (LinuxServer.io)
    sk_SK: Keepassxc (LinuxServer.io)
    sv_SE: Keepassxc (LinuxServer.io)
    tr_TR: Keepassxc (LinuxServer.io)
    zh_CN: Keepassxc（LinuxServer.io）
    zh_TW: Keepassxc（LinuxServer.io）
  id: by-roket.linuxserver.keepassxc
  port_map: '3000'
  version: 2.7.12
  index: /
