name: linuxserver-headphones
services:
  headphones:
    image: linuxserver/headphones:version-a78f38c1@sha256:738be7eefa1ead8a869bdf6393b0ee5008149a1c4dc9faa8720467d2dc21c6ec
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/headphones/config
        target: /config
      - type: bind
        source: /DATA/AppData/headphones/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/headphones/music
        target: /music
x-casaos:
  main: headphones
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.headphones/assets/icon.png
  title:
    en_US: Headphones
  port_map: '8181'
  id: by-roket.linuxserver.headphones
  version: version-a78f38c1
  index: /
