name: linuxserver-headphones
services:
  headphones:
    image: linuxserver/headphones:version-a78f38c1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/$AppID/music
        target: /music
    container_name: headphones-by-roket
x-casaos:
  main: headphones
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.headphones/assets/icon.png
  title:
    en_US: Headphones
    zh_CN: Headphones
    ca_ES: Headphones
    cs_CZ: Headphones
    da_DK: Headphones
    de_DE: Headphones
    el_GR: Headphones
    en_GB: Headphones
    es_ES: Headphones
    fr_FR: Headphones
    ga_IE: Headphones
    hr_HR: Headphones
    hu_HU: Headphones
    it_IT: Headphones
    ja_JP: Headphones
    ko_KR: Headphones
    ml_IN: Headphones
    nb_NO: Headphones
    nl_NL: Headphones
    pl_PL: Headphones
    pt_BR: Headphones
    ro_RO: Headphones
    ru_RU: Headphones
    sk_SK: Headphones
    sv_SE: Headphones
    tr_TR: Headphones
    zh_TW: Headphones
  port_map: '8181'
  id: by-roket.linuxserver.headphones
  version: version-a78f38c1
  index: /
