name: linuxserver-vivaldi
services:
  vivaldi:
    image: linuxserver/vivaldi:8.1.4087@sha256:afcf095d15d498ea80b5788fe0cb05595672f2bb4fc42b2fd10a508776fcf161
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VIVALDI_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
x-casaos:
  main: vivaldi
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.vivaldi/assets/icon.png
  title:
    en_US: Vivaldi
  port_map: '3000'
  id: by-roket.linuxserver.vivaldi
  version: 8.1.4087
  index: /
