name: linuxserver-telegram
services:
  telegram:
    image: linuxserver/telegram:7.0.9@sha256:99cff6300045ed9aa474e3f01c7011ea629adad6d5330ec240f335456aa58788
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: telegram-by-roket
x-casaos:
  main: telegram
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.telegram/assets/icon.png
  title:
    en_US: Telegram (LinuxServer.io)
  id: by-roket.linuxserver.telegram
  port_map: '3000'
  version: 7.0.9
  index: /
