name: linuxserver-melonds
services:
  melonds:
    image: linuxserver/melonds:1.1.20260907@sha256:3f04588c4734aad14b1fccfc0c4c859ca109fef7364100eaa7459de087b319e7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: melonds-by-roket
x-casaos:
  main: melonds
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.melonds/assets/icon.png
  title:
    en_US: Melonds (LinuxServer.io)
  id: by-roket.linuxserver.melonds
  port_map: '3000'
  version: 1.1.20260907
  index: /
