name: linuxserver-doplarr
services:
  doplarr:
    image: linuxserver/doplarr:3.8.0@sha256:50226d0f4204aca24194803de959c57cecad03411e06d845f0da473fd6b9607a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DISCORD__TOKEN: ''
      OVERSEERR__API: ''
      OVERSEERR__URL: ''
      RADARR__API: ''
      RADARR__URL: ''
      SONARR__API: ''
      SONARR__URL: ''
      DISCORD__MAX_RESULTS: ''
      DISCORD__REQUESTED_MSG_STYLE: ''
      SONARR__QUALITY_PROFILE: ''
      RADARR__QUALITY_PROFILE: ''
      SONARR__ROOTFOLDER: ''
      RADARR__ROOTFOLDER: ''
      SONARR__LANGUAGE_PROFILE: ''
      OVERSEERR__DEFAULT_ID: ''
      PARTIAL_SEASONS: ''
      LOG_LEVEL: ''
      JAVA_OPTS: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: doplarr-by-roket
x-casaos:
  main: doplarr
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.doplarr/assets/icon.png
  title:
    en_US: Doplarr
  port_map: '80'
  id: by-roket.linuxserver.doplarr
  version: 3.8.0
  index: /
