name: linuxserver-apprise-api
services:
  apprise-api:
    image: linuxserver/apprise-api:1.5.4@sha256:f6e7997b5ae76d78499f28fe19a89d1556615c94e2a81089fdb344082b23bda6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APPRISE_ATTACH_SIZE: ''
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/attachments
        target: /attachments
    container_name: apprise-api-by-roket
x-casaos:
  main: apprise-api
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.apprise-api/assets/icon.png
  title:
    en_US: Apprise api (LinuxServer.io)
    ca_ES: Apprise api (LinuxServer.io)
    cs_CZ: Apprise api (LinuxServer.io)
    da_DK: Apprise api (LinuxServer.io)
    de_DE: Apprise api (LinuxServer.io)
    el_GR: Apprise api (LinuxServer.io)
    en_GB: Apprise api (LinuxServer.io)
    es_ES: Apprise api (LinuxServer.io)
    fr_FR: Apprise api (LinuxServer.io)
    ga_IE: Apprise api (LinuxServer.io)
    hr_HR: Apprise api (LinuxServer.io)
    hu_HU: Apprise api (LinuxServer.io)
    it_IT: Apprise api (LinuxServer.io)
    ja_JP: Apprise api (LinuxServer.io)
    ko_KR: Apprise api (LinuxServer.io)
    ml_IN: Apprise api (LinuxServer.io)
    nb_NO: Apprise api (LinuxServer.io)
    nl_NL: Apprise api (LinuxServer.io)
    pl_PL: Apprise api (LinuxServer.io)
    pt_BR: Apprise api (LinuxServer.io)
    ro_RO: Apprise api (LinuxServer.io)
    ru_RU: Apprise api (LinuxServer.io)
    sk_SK: Apprise api (LinuxServer.io)
    sv_SE: Apprise api (LinuxServer.io)
    tr_TR: Apprise api (LinuxServer.io)
    zh_CN: Apprise api（LinuxServer.io）
    zh_TW: Apprise api（LinuxServer.io）
  id: by-roket.linuxserver.apprise-api
  port_map: '8000'
  version: 1.5.4
  index: /
