name: linuxserver-apprise-api
services:
  apprise-api:
    image: linuxserver/apprise-api:1.5.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APPRISE_ATTACH_SIZE: ''
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/attachments
        target: /attachments
    container_name: apprise-api-by-roket
x-casaos:
  main: apprise-api
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.apprise-api/assets/icon.png
  title:
    en_US: Apprise api (LinuxServer.io)
  id: by-roket.linuxserver.apprise-api
  port_map: '8000'
  version: 1.5.3
  index: /
