name: linuxserver-github-desktop
services:
  github-desktop:
    image: linuxserver/github-desktop:3.4.13@sha256:88f57d5b82ca758cf9a8fde22a3ee84a7c3ff1ca90a7eabe5255481f02dfc4b9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: github-desktop-by-roket
x-casaos:
  main: github-desktop
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.github-desktop/assets/icon.png
  title:
    en_US: Github desktop
  port_map: '3000'
  id: by-roket.linuxserver.github-desktop
  version: 3.4.13
  index: /
