name: linuxserver-adguardhome-sync
services:
  adguardhome-sync:
    image: linuxserver/adguardhome-sync:0.9.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONFIGFILE: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: adguardhome-sync-by-roket
x-casaos:
  main: adguardhome-sync
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.adguardhome-sync/assets/icon.png
  title:
    en_US: Adguardhome sync (LinuxServer.io)
  id: by-roket.linuxserver.adguardhome-sync
  port_map: '8080'
  version: 0.9.2
  index: /
