name: linuxserver-vscodium-web
services:
  vscodium-web:
    image: linuxserver/vscodium-web:1.126.04524@sha256:836f99a155ad0ca08316685e4c27792fb91c89586b36db6b0555d1ff71c4fbcd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONNECTION_TOKEN: ''
      CONNECTION_TOKEN_FILE: ''
      SUDO_PASSWORD: ''
      SUDO_PASSWORD_HASH: ''
      CODE_ARGS: ''
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: vscodium-web-by-roket
x-casaos:
  main: vscodium-web
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.vscodium-web/assets/icon.png
  title:
    en_US: Vscodium web
  port_map: '8000'
  id: by-roket.linuxserver.vscodium-web
  version: 1.126.04524
  index: /
