name: linuxserver-transmission
services:
  transmission:
    image: linuxserver/transmission:4.1.3@sha256:50ef01aa91e21db7f466ba763fb035d321bca03c0daf3c4a875f0d848184d6c9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TRANSMISSION_WEB_HOME: ''
      USER: ''
      PASS: ''
      WHITELIST: ''
      PEERPORT: ''
      HOST_WHITELIST: ''
    ports:
      - target: 9091
        published: 9091
        protocol: tcp
      - target: 51413
        published: 51413
        protocol: tcp
      - target: 51413
        published: 51413
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/transmission/config
        target: /config
      - type: bind
        source: /DATA/AppData/transmission/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/transmission/watch
        target: /watch
x-casaos:
  main: transmission
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.transmission/assets/icon.png
  title:
    en_US: Transmission
  id: by-roket.linuxserver.transmission
  version: 4.1.3
  index: /
  port_map: '9091'
