name: linuxserver-transmission
services:
  transmission:
    image: linuxserver/transmission:4.1.3@sha256:5d851a61371e8120b9e1dbe338b4f21802a24c5565598f7e8dd896b9b6a70874
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TRANSMISSION_WEB_HOME: ''
      USER: ''
      PASS: ''
      WHITELIST: ''
      PEERPORT: ''
      HOST_WHITELIST: ''
    ports:
      - target: 9091
        published: 9091
        protocol: tcp
      - target: 51413
        published: 51413
        protocol: tcp
      - target: 51413
        published: 51413
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/$AppID/watch
        target: /watch
    container_name: transmission-by-roket
x-casaos:
  main: transmission
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.transmission/assets/icon.png
  title:
    en_US: Transmission
  id: by-roket.linuxserver.transmission
  version: 4.1.3
  index: /
  port_map: '9091'
