name: linuxserver-calibre
services:
  calibre:
    image: linuxserver/calibre:9.13.0@sha256:352cabf94c6c62def8dff3b3e1cc34a6ed6d99c516eec35208a56b1d1ce1d7e5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      CLI_ARGS: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8181
        published: 8181
        protocol: tcp
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/calibre/config
        target: /config
x-casaos:
  main: calibre
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.calibre/assets/icon.png
  title:
    en_US: Calibre
  port_map: '8080'
  id: by-roket.linuxserver.calibre
  version: 9.13.0
  index: /
