name: linuxserver-synclounge
services:
  synclounge:
    image: linuxserver/synclounge:5.2.35
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/synclounge/config
        target: /config
x-casaos:
  main: synclounge
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.synclounge/assets/icon.png
  title:
    en_US: Synclounge
  port_map: '8088'
  id: by-roket.linuxserver.synclounge
  version: 5.2.35
  index: /
