name: linuxserver-synclounge
services:
  synclounge:
    image: linuxserver/synclounge:5.2.35@sha256:affeedb85068dd1990abcdb904a91544a4f3ecb736d3ac33ca4c3e743a659281
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: synclounge-by-roket
x-casaos:
  main: synclounge
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.synclounge/assets/icon.png
  title:
    en_US: Synclounge (LinuxServer.io)
    ca_ES: Synclounge (LinuxServer.io)
    cs_CZ: Synclounge (LinuxServer.io)
    da_DK: Synclounge (LinuxServer.io)
    de_DE: Synclounge (LinuxServer.io)
    el_GR: Synclounge (LinuxServer.io)
    en_GB: Synclounge (LinuxServer.io)
    es_ES: Synclounge (LinuxServer.io)
    fr_FR: Synclounge (LinuxServer.io)
    ga_IE: Synclounge (LinuxServer.io)
    hr_HR: Synclounge (LinuxServer.io)
    hu_HU: Synclounge (LinuxServer.io)
    it_IT: Synclounge (LinuxServer.io)
    ja_JP: Synclounge (LinuxServer.io)
    ko_KR: Synclounge (LinuxServer.io)
    ml_IN: Synclounge (LinuxServer.io)
    nb_NO: Synclounge (LinuxServer.io)
    nl_NL: Synclounge (LinuxServer.io)
    pl_PL: Synclounge (LinuxServer.io)
    pt_BR: Synclounge (LinuxServer.io)
    ro_RO: Synclounge (LinuxServer.io)
    ru_RU: Synclounge (LinuxServer.io)
    sk_SK: Synclounge (LinuxServer.io)
    sv_SE: Synclounge (LinuxServer.io)
    tr_TR: Synclounge (LinuxServer.io)
    zh_CN: Synclounge（LinuxServer.io）
    zh_TW: Synclounge（LinuxServer.io）
  id: by-roket.linuxserver.synclounge
  port_map: '8088'
  version: 5.2.35
  index: /
