name: linuxserver-code-server
services:
  code-server:
    image: linuxserver/code-server:4.135.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      HASHED_PASSWORD: ''
      SUDO_PASSWORD: ''
      SUDO_PASSWORD_HASH: ''
      PROXY_DOMAIN: ''
      DEFAULT_WORKSPACE: ''
      PWA_APPNAME: ''
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: code-server-by-roket
x-casaos:
  main: code-server
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.code-server/assets/icon.png
  title:
    en_US: Code server
  port_map: '8443'
  id: by-roket.linuxserver.code-server
  version: 4.135.0
  index: /
