name: linuxserver-sickchill
services:
  sickchill:
    image: linuxserver/sickchill:2024.3.1@sha256:78d0b0055b5fc1bdb0a49db19ca61c7d76bc9087baadb8fee8b8e835ac696384
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/$AppID/tv
        target: /tv
    container_name: sickchill-by-roket
x-casaos:
  main: sickchill
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.sickchill/assets/icon.png
  title:
    en_US: Sickchill
  port_map: '8081'
  id: by-roket.linuxserver.sickchill
  version: 2024.3.1
  index: /
