name: linuxserver-mylar3
services:
  mylar3:
    image: linuxserver/mylar3:0.11.0@sha256:c35326af07ae596f3347b5ad27e84358c294f9bef2f3e06646bb36c9d88fafaa
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8090
        published: 8090
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/comics
        target: /comics
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: mylar3-by-roket
x-casaos:
  main: mylar3
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.mylar3/assets/icon.png
  title:
    en_US: Mylar3
  port_map: '8090'
  id: by-roket.linuxserver.mylar3
  version: 0.11.0
  index: /
