name: linuxserver-heimdall
services:
  heimdall:
    image: linuxserver/heimdall:2.8.2@sha256:dc10227f04c9e6afa49ef305ef87d905481659ce2b3059d51c5e2719d982d292
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ALLOW_INTERNAL_REQUESTS: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: heimdall-by-roket
x-casaos:
  main: heimdall
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.heimdall/assets/icon.png
  title:
    en_US: Heimdall
  port_map: '80'
  id: by-roket.linuxserver.heimdall
  version: 2.8.2
  index: /
