name: linuxserver-htpcmanager
services:
  htpcmanager:
    image: linuxserver/htpcmanager:version-26a641bf@sha256:f7c11027672fd271b24954c37d2f23f3d9e4937a2b4e70b1645ded76f72eecbe
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: htpcmanager-by-roket
x-casaos:
  main: htpcmanager
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.htpcmanager/assets/icon.png
  title:
    en_US: Htpcmanager (LinuxServer.io)
  id: by-roket.linuxserver.htpcmanager
  port_map: '8085'
  version: version-26a641bf
  index: /
