name: linuxserver-unrar
services:
  unrar:
    image: linuxserver/unrar:7.0.9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: unrar-by-roket
x-casaos:
  main: unrar
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.unrar/assets/icon.png
  title:
    en_US: Unrar
  port_map: '80'
  id: by-roket.linuxserver.unrar
  version: 7.0.9
  index: /
