name: linuxserver-kavita
services:
  kavita:
    image: linuxserver/kavita:0.9.1@sha256:2dbe04d899a2128c8f0c57917e79ddec2199c7e75a323f5aa693c0ab25acb714
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: kavita-by-roket
x-casaos:
  main: kavita
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.kavita/assets/icon.png
  title:
    en_US: Kavita (LinuxServer.io)
  id: by-roket.linuxserver.kavita
  port_map: '5000'
  version: 0.9.1
  index: /
