name: linuxserver-homeassistant
services:
  homeassistant:
    image: linuxserver/homeassistant:2026.8.3@sha256:ee635ba757829abe3061b3fb77cf76fa92368d726393ac201c85d5391180fe0d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8123
        published: 8123
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: homeassistant-by-roket
x-casaos:
  main: homeassistant
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.homeassistant/assets/icon.png
  title:
    en_US: Homeassistant
  port_map: '8123'
  id: by-roket.linuxserver.homeassistant
  version: 2026.8.3
  index: /
