name: linuxserver-homeassistant
services:
  homeassistant:
    image: linuxserver/homeassistant:2026.9.0@sha256:d7247aa3658fc2715aeda9f225f4a0598d7bfc87d444ea2dee7f1500cadd386b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8123
        published: 8123
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: homeassistant-by-roket
x-casaos:
  main: homeassistant
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.homeassistant/assets/icon.png
  title:
    en_US: Homeassistant (LinuxServer.io)
  id: by-roket.linuxserver.homeassistant
  port_map: '8123'
  version: 2026.9.0
  index: /
