name: linuxserver-socket-proxy
services:
  socket-proxy:
    image: linuxserver/socket-proxy:3.4.4@sha256:51eb58d4082daf44c50b381c5739dd6f4b3e667e7f9e10f3d16d977894df969e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: socket-proxy-by-roket
x-casaos:
  main: socket-proxy
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.socket-proxy/assets/icon.png
  title:
    en_US: Socket proxy (LinuxServer.io)
  id: by-roket.linuxserver.socket-proxy
  port_map: '80'
  version: 3.4.4
  index: /
