name: linuxserver-socket-proxy
services:
  socket-proxy:
    image: linuxserver/socket-proxy:3.4.3@sha256:c98ce91dc40e2ab4c13beba78089cd3d8455119c074b0d4e9234cf68b5679c02
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: socket-proxy-by-roket
x-casaos:
  main: socket-proxy
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.socket-proxy/assets/icon.png
  title:
    en_US: Socket proxy
  port_map: '80'
  id: by-roket.linuxserver.socket-proxy
  version: 3.4.3
  index: /
