name: linuxserver-flexget
services:
  flexget:
    image: linuxserver/flexget:3.20.9@sha256:1799701dc451b681b107cc7a41db0c9a235edb903b6ad51409c3b4fbf8a5eb61
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FG_LOG_LEVEL: ''
      FG_LOG_FILE: ''
      FG_CONFIG_FILE: ''
      FG_WEBUI_PASSWORD: ''
    ports:
      - target: 5050
        published: 5050
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: flexget-by-roket
x-casaos:
  main: flexget
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.flexget/assets/icon.png
  title:
    en_US: Flexget (LinuxServer.io)
  id: by-roket.linuxserver.flexget
  port_map: '5050'
  version: 3.20.9
  index: /
