name: linuxserver-flexget
services:
  flexget:
    image: linuxserver/flexget:3.20.6@sha256:2d812d6e09c1bb71046f7f5844335b199464ca08f4f8a3b82b9a0ad59297c6d4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FG_LOG_LEVEL: ''
      FG_LOG_FILE: ''
      FG_CONFIG_FILE: ''
      FG_WEBUI_PASSWORD: ''
    ports:
      - target: 5050
        published: 5050
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: flexget-by-roket
x-casaos:
  main: flexget
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.flexget/assets/icon.png
  title:
    en_US: Flexget
  port_map: '5050'
  id: by-roket.linuxserver.flexget
  version: 3.20.6
  index: /
