#!/usr/bin/env python3
"""Check the deployed layout generated by the official ZimaOS V2 builder."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


def read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        value = json.load(handle)

    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object in {path}")

    return value


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify generated ZimaOS V2 store artifacts."
    )
    parser.add_argument("--source", default=".")
    parser.add_argument("--dist", default="dist")
    parser.add_argument("--base-url", default="")
    arguments = parser.parse_args()

    source = Path(arguments.source)
    dist = Path(arguments.dist)
    errors: list[str] = []

    required_files = (
        dist / "store.json",
        dist / "index.json",
        dist / "metadata.tar.gz",
        dist / "metadata.sha256",
    )

    for path in required_files:
        if not path.is_file():
            errors.append(f"Missing required generated file: {path}")

    apps_output = dist / "apps"

    if not apps_output.is_dir():
        errors.append(f"Missing required generated directory: {apps_output}")

    if errors:
        for error in errors:
            print(f"[ERROR] {error}", file=sys.stderr)

        return 1

    store = read_json(dist / "store.json")
    index = read_json(dist / "index.json")
    store_config = read_json(source / "store-config.json")

    if store.get("version") != 2:
        errors.append("store.json does not declare protocol version 2")

    if index.get("version") != 2:
        errors.append("index.json does not declare protocol version 2")

    if store.get("store_id") != store_config.get("store_id"):
        errors.append("Generated store_id differs from store-config.json")

    expected_base_url = arguments.base_url.rstrip("/")
    actual_base_url = str(index.get("base_url", "")).rstrip("/")

    if expected_base_url and actual_base_url != expected_base_url:
        errors.append(
            f"Unexpected base URL: expected {expected_base_url}, "
            f"got {actual_base_url}"
        )

    source_apps = [
        directory
        for directory in (source / "Apps").iterdir()
        if directory.is_dir()
        and (
            (directory / "docker-compose.yml").is_file()
            or (directory / "docker-compose.yaml").is_file()
        )
    ]
    applications = index.get("apps")

    if not isinstance(applications, list):
        errors.append("index.json does not contain an application list")
        applications = []

    if index.get("app_count") != len(applications):
        errors.append("index.json app_count does not match its app list")

    if len(applications) != len(source_apps):
        errors.append(
            f"Source contains {len(source_apps)} apps but "
            f"index.json contains {len(applications)}"
        )

    for application in applications:
        if not isinstance(application, dict):
            errors.append("Invalid application entry in index.json")
            continue

        app_id = application.get("id")

        if not isinstance(app_id, str) or not app_id:
            errors.append("Application entry is missing its identifier")
            continue

        app_directory = apps_output / app_id

        for filename in ("docker-compose.yml", "meta.json"):
            if not (app_directory / filename).is_file():
                errors.append(
                    f"Application {app_id} is missing {filename}"
                )

        if not (app_directory / "assets").is_dir():
            errors.append(f"Application {app_id} has no assets directory")

    french_fields = any(
        isinstance(store_config.get(field), dict)
        and "fr_FR" in store_config[field]
        for field in ("name", "description")
    )

    if french_fields and not (dist / "store.fr_FR.json").is_file():
        errors.append("French store metadata store.fr_FR.json was not generated")

    if errors:
        for error in errors:
            print(f"[ERROR] {error}", file=sys.stderr)

        print(f"Generated store verification failed: {len(errors)} error(s).")
        return 1

    print(f"Store ID: {store['store_id']}")
    print(f"Protocol version: {store['version']}")
    print(f"Applications verified: {len(applications)}")
    print(f"French store metadata: {'yes' if french_fields else 'not requested'}")
    print(f"Base URL: {actual_base_url}")
    print("Generated ZimaOS V2 store layout: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
