name: linuxserver-tautulli
services:
  tautulli:
    image: linuxserver/tautulli:2.18.0@sha256:01d494167b0c9ce633648ac9c9377cce376ad851b6289039bae72f51a6d2041c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: tautulli-by-roket
x-casaos:
  main: tautulli
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.tautulli/assets/icon.png
  title:
    en_US: Tautulli
  port_map: '8181'
  id: by-roket.linuxserver.tautulli
  version: 2.18.0
  index: /
