name: linuxserver-tautulli
services:
  tautulli:
    image: linuxserver/tautulli:2.18.1@sha256:4e9a789e744cbf878d1f40fbba3e99b5db32efbbf7fe71370f6c9586d009c0df
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: tautulli-by-roket
x-casaos:
  main: tautulli
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.tautulli/assets/icon.png
  title:
    en_US: Tautulli (LinuxServer.io)
  id: by-roket.linuxserver.tautulli
  port_map: '8181'
  version: 2.18.1
  index: /
