name: linuxserver-tautulli
services:
  tautulli:
    image: linuxserver/tautulli:2.17.2@sha256:601e90b4dfeaf1bad9f99e9c8c76ad30a9693c1cb7eec335d5e26cc824cb23cf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: tautulli-by-roket
x-casaos:
  main: tautulli
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.tautulli/assets/icon.png
  title:
    en_US: Tautulli
  port_map: '8181'
  id: by-roket.linuxserver.tautulli
  version: 2.17.2
  index: /
