name: linuxserver-lidarr
services:
  lidarr:
    image: linuxserver/lidarr:3.1.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8686
        published: 8686
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/music
        target: /music
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    container_name: lidarr-by-roket
x-casaos:
  main: lidarr
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.lidarr/assets/icon.png
  title:
    en_US: Lidarr (LinuxServer.io)
  id: by-roket.linuxserver.lidarr
  port_map: '8686'
  version: 3.1.0
  index: /
