name: linuxserver-endlessh
services:
  endlessh:
    image: linuxserver/endlessh:version-dfe44eb2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MSDELAY: ''
      MAXLINES: ''
      MAXCLIENTS: ''
      LOGFILE: ''
      BINDFAMILY: ''
    ports:
      - target: 22
        published: 2222
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/endlessh/config
        target: /config
      - type: bind
        source: /DATA/AppData/endlessh/config
        target: /config
x-casaos:
  main: endlessh
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.endlessh/assets/icon.png
  title:
    en_US: Endlessh
  port_map: '8080'
  id: by-roket.linuxserver.endlessh
  version: version-dfe44eb2
  index: /
