name: linuxserver-mediaelch
services:
  mediaelch:
    image: linuxserver/mediaelch:2.12.0@sha256:85774c5e0fa3a635a8a3b9c96da924b0ac2fa1f01e49e30e068374b9d8e79e72
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: mediaelch-by-roket
x-casaos:
  main: mediaelch
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.mediaelch/assets/icon.png
  title:
    en_US: Mediaelch (LinuxServer.io)
    ca_ES: Mediaelch (LinuxServer.io)
    cs_CZ: Mediaelch (LinuxServer.io)
    da_DK: Mediaelch (LinuxServer.io)
    de_DE: Mediaelch (LinuxServer.io)
    el_GR: Mediaelch (LinuxServer.io)
    en_GB: Mediaelch (LinuxServer.io)
    es_ES: Mediaelch (LinuxServer.io)
    fr_FR: Mediaelch (LinuxServer.io)
    ga_IE: Mediaelch (LinuxServer.io)
    hr_HR: Mediaelch (LinuxServer.io)
    hu_HU: Mediaelch (LinuxServer.io)
    it_IT: Mediaelch (LinuxServer.io)
    ja_JP: Mediaelch (LinuxServer.io)
    ko_KR: Mediaelch (LinuxServer.io)
    ml_IN: Mediaelch (LinuxServer.io)
    nb_NO: Mediaelch (LinuxServer.io)
    nl_NL: Mediaelch (LinuxServer.io)
    pl_PL: Mediaelch (LinuxServer.io)
    pt_BR: Mediaelch (LinuxServer.io)
    ro_RO: Mediaelch (LinuxServer.io)
    ru_RU: Mediaelch (LinuxServer.io)
    sk_SK: Mediaelch (LinuxServer.io)
    sv_SE: Mediaelch (LinuxServer.io)
    tr_TR: Mediaelch (LinuxServer.io)
    zh_CN: Mediaelch（LinuxServer.io）
    zh_TW: Mediaelch（LinuxServer.io）
  id: by-roket.linuxserver.mediaelch
  port_map: '3000'
  version: 2.12.0
  index: /
