name: linuxserver-mediaelch
services:
  mediaelch:
    image: linuxserver/mediaelch:2.12.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mediaelch/config
        target: /config
x-casaos:
  main: mediaelch
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.mediaelch/assets/icon.png
  title:
    en_US: Mediaelch
  port_map: '3000'
  id: by-roket.linuxserver.mediaelch
  version: 2.12.0
  index: /
