name: linuxserver-ferdium
services:
  ferdium:
    image: linuxserver/ferdium:7.2.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: ferdium-by-roket
x-casaos:
  main: ferdium
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ferdium/assets/icon.png
  title:
    en_US: Ferdium (LinuxServer.io)
  id: by-roket.linuxserver.ferdium
  port_map: '3000'
  version: 7.2.2
  index: /
