name: linuxserver-ferdium
services:
  ferdium:
    image: linuxserver/ferdium:7.2.1@sha256:f3cac8420764a7a79642e34635090842c4ed9c53867e0068ba3ea9fe559ac09f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: ferdium-by-roket
x-casaos:
  main: ferdium
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.ferdium/assets/icon.png
  title:
    en_US: Ferdium
  port_map: '3000'
  id: by-roket.linuxserver.ferdium
  version: 7.2.1
  index: /
