name: linuxserver-calibre-web
services:
  calibre-web:
    image: linuxserver/calibre-web:0.6.27@sha256:fb953f1b46aee37342b147fbc2ed9fbcee1e941008a61b5626b69dee78aa00e8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: ''
      OAUTHLIB_RELAX_TOKEN_SCOPE: ''
    ports:
      - target: 8083
        published: 8083
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/books
        target: /books
    container_name: calibre-web-by-roket
x-casaos:
  main: calibre-web
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.calibre-web/assets/icon.png
  title:
    en_US: Calibre web (LinuxServer.io)
  id: by-roket.linuxserver.calibre-web
  port_map: '8083'
  version: 0.6.27
  index: /
