name: linuxserver-duplicati
services:
  duplicati:
    image: linuxserver/duplicati:2.4.0@sha256:fc3a1a0e8519c9c99d247bcfd9944743659830379ce68a842edd46bf209ad96f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SETTINGS_ENCRYPTION_KEY: ''
      CLI_ARGS: ''
      DUPLICATI__WEBSERVICE_PASSWORD: ''
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/backups
        target: /backups
      - type: bind
        source: /DATA/AppData/$AppID/source
        target: /source
    container_name: duplicati-by-roket
x-casaos:
  main: duplicati
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.duplicati/assets/icon.png
  title:
    en_US: Duplicati (LinuxServer.io)
    ca_ES: Duplicati (LinuxServer.io)
    cs_CZ: Duplicati (LinuxServer.io)
    da_DK: Duplicati (LinuxServer.io)
    de_DE: Duplicati (LinuxServer.io)
    el_GR: Duplicati (LinuxServer.io)
    en_GB: Duplicati (LinuxServer.io)
    es_ES: Duplicati (LinuxServer.io)
    fr_FR: Duplicati (LinuxServer.io)
    ga_IE: Duplicati (LinuxServer.io)
    hr_HR: Duplicati (LinuxServer.io)
    hu_HU: Duplicati (LinuxServer.io)
    it_IT: Duplicati (LinuxServer.io)
    ja_JP: Duplicati (LinuxServer.io)
    ko_KR: Duplicati (LinuxServer.io)
    ml_IN: Duplicati (LinuxServer.io)
    nb_NO: Duplicati (LinuxServer.io)
    nl_NL: Duplicati (LinuxServer.io)
    pl_PL: Duplicati (LinuxServer.io)
    pt_BR: Duplicati (LinuxServer.io)
    ro_RO: Duplicati (LinuxServer.io)
    ru_RU: Duplicati (LinuxServer.io)
    sk_SK: Duplicati (LinuxServer.io)
    sv_SE: Duplicati (LinuxServer.io)
    tr_TR: Duplicati (LinuxServer.io)
    zh_CN: Duplicati（LinuxServer.io）
    zh_TW: Duplicati（LinuxServer.io）
  id: by-roket.linuxserver.duplicati
  port_map: '8200'
  version: 2.4.0
  index: /
