name: linuxserver-duplicati
services:
  duplicati:
    image: linuxserver/duplicati:2.4.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SETTINGS_ENCRYPTION_KEY: ''
      CLI_ARGS: ''
      DUPLICATI__WEBSERVICE_PASSWORD: ''
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/backups
        target: /backups
      - type: bind
        source: /DATA/AppData/$AppID/source
        target: /source
    container_name: duplicati-by-roket
x-casaos:
  main: duplicati
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.duplicati/assets/icon.png
  title:
    en_US: Duplicati (LinuxServer.io)
  id: by-roket.linuxserver.duplicati
  port_map: '8200'
  version: 2.4.0
  index: /
