name: linuxserver-modmanager
services:
  modmanager:
    image: linuxserver/modmanager:version-8da40b7a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: modmanager-by-roket
x-casaos:
  main: modmanager
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.modmanager/assets/icon.png
  title:
    en_US: Modmanager (LinuxServer.io)
  id: by-roket.linuxserver.modmanager
  port_map: '80'
  version: version-8da40b7a
  index: /
