name: linuxserver-remmina
services:
  remmina:
    image: linuxserver/remmina:1.4.40@sha256:988ee9d05c2d88feeee2a0a81e1798ec89f313c6a4fd54f9848a02809e253b92
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: remmina-by-roket
x-casaos:
  main: remmina
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.remmina/assets/icon.png
  title:
    en_US: Remmina
  port_map: '3000'
  id: by-roket.linuxserver.remmina
  version: 1.4.40
  index: /
