name: linuxserver-remmina
services:
  remmina:
    image: linuxserver/remmina:1.4.43@sha256:19a086b1a8c3eecc736064c2351f6cc4b46b77e025387c44c3eb9a99a94e4186
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: remmina-by-roket
x-casaos:
  main: remmina
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.remmina/assets/icon.png
  title:
    en_US: Remmina
  port_map: '3000'
  id: by-roket.linuxserver.remmina
  version: 1.4.43
  index: /
