name: linuxserver-piper
services:
  piper:
    image: linuxserver/piper:2.4.2@sha256:b278729ffad60c1e9058a55595aa31a58ded871ff37f2b94648eb13ebf1922f0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PIPER_VOICE: ''
      LOCAL_ONLY: ''
      PIPER_LENGTH: ''
      PIPER_NOISE: ''
      PIPER_NOISEW: ''
      PIPER_SPEAKER: ''
      NO_STREAMING: ''
    ports:
      - target: 10200
        published: 10200
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/piper/config
        target: /config
x-casaos:
  main: piper
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.piper/assets/icon.png
  title:
    en_US: Piper
  port_map: '10200'
  id: by-roket.linuxserver.piper
  version: 2.4.2
  index: /
