name: linuxserver-manyfold
services:
  manyfold:
    image: linuxserver/manyfold:0.147.2@sha256:8f844bd31c59f212206ffd2f5617da3569bf7ef779ff9878aa08396a1d6b3d37
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DATABASE_URL: ''
      REDIS_URL: ''
      SECRET_KEY_BASE: ''
    ports:
      - target: 3214
        published: 3214
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/manyfold/config
        target: /config
      - type: bind
        source: /DATA/AppData/manyfold/libraries
        target: /libraries
x-casaos:
  main: manyfold
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.manyfold/assets/icon.png
  title:
    en_US: Manyfold
  port_map: '3214'
  id: by-roket.linuxserver.manyfold
  version: 0.147.2
  index: /
