name: linuxserver-manyfold
services:
  manyfold:
    image: linuxserver/manyfold:0.148.0@sha256:ed1414de168518e85e5a843555c1454f314380243458435dff9e94715985a2ed
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DATABASE_URL: ''
      REDIS_URL: ''
      SECRET_KEY_BASE: ''
    ports:
      - target: 3214
        published: 3214
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/libraries
        target: /libraries
    container_name: manyfold-by-roket
x-casaos:
  main: manyfold
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.manyfold/assets/icon.png
  title:
    en_US: Manyfold (LinuxServer.io)
  id: by-roket.linuxserver.manyfold
  port_map: '3214'
  version: 0.148.0
  index: /
