name: linuxserver-manyfold
services:
  manyfold:
    image: linuxserver/manyfold:0.150.0@sha256:c1053139eb4f1473189116fa25d930dd49d1bca7d523a06ccb5a3ea74677148f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DATABASE_URL: ''
      REDIS_URL: ''
      SECRET_KEY_BASE: ''
    ports:
      - target: 3214
        published: 3214
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/libraries
        target: /libraries
    container_name: manyfold-by-roket
x-casaos:
  main: manyfold
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.manyfold/assets/icon.png
  title:
    en_US: Manyfold (LinuxServer.io)
    ca_ES: Manyfold (LinuxServer.io)
    cs_CZ: Manyfold (LinuxServer.io)
    da_DK: Manyfold (LinuxServer.io)
    de_DE: Manyfold (LinuxServer.io)
    el_GR: Manyfold (LinuxServer.io)
    en_GB: Manyfold (LinuxServer.io)
    es_ES: Manyfold (LinuxServer.io)
    fr_FR: Manyfold (LinuxServer.io)
    ga_IE: Manyfold (LinuxServer.io)
    hr_HR: Manyfold (LinuxServer.io)
    hu_HU: Manyfold (LinuxServer.io)
    it_IT: Manyfold (LinuxServer.io)
    ja_JP: Manyfold (LinuxServer.io)
    ko_KR: Manyfold (LinuxServer.io)
    ml_IN: Manyfold (LinuxServer.io)
    nb_NO: Manyfold (LinuxServer.io)
    nl_NL: Manyfold (LinuxServer.io)
    pl_PL: Manyfold (LinuxServer.io)
    pt_BR: Manyfold (LinuxServer.io)
    ro_RO: Manyfold (LinuxServer.io)
    ru_RU: Manyfold (LinuxServer.io)
    sk_SK: Manyfold (LinuxServer.io)
    sv_SE: Manyfold (LinuxServer.io)
    tr_TR: Manyfold (LinuxServer.io)
    zh_CN: Manyfold（LinuxServer.io）
    zh_TW: Manyfold（LinuxServer.io）
  id: by-roket.linuxserver.manyfold
  port_map: '3214'
  version: 0.150.0
  index: /
