name: linuxserver-manyfold
services:
  manyfold:
    image: linuxserver/manyfold:0.147.2@sha256:0e620aeac102c812bbb9d3f4ad04534bda8959f40e0bd6b8526b8215fcddd306
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DATABASE_URL: ''
      REDIS_URL: ''
      SECRET_KEY_BASE: ''
    ports:
      - target: 3214
        published: 3214
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/libraries
        target: /libraries
    container_name: manyfold-by-roket
x-casaos:
  main: manyfold
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.manyfold/assets/icon.png
  title:
    en_US: Manyfold
  port_map: '3214'
  id: by-roket.linuxserver.manyfold
  version: 0.147.2
  index: /
