name: linuxserver-pairdrop
services:
  pairdrop:
    image: linuxserver/pairdrop:1.11.2@sha256:562c48f55e68416f04a71abdeb1e719ed07966584722a34f1aa2b317e4c11871
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RATE_LIMIT: ''
      WS_FALLBACK: ''
      RTC_CONFIG: ''
      DEBUG_MODE: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: pairdrop-by-roket
x-casaos:
  main: pairdrop
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.pairdrop/assets/icon.png
  title:
    en_US: Pairdrop (LinuxServer.io)
  id: by-roket.linuxserver.pairdrop
  port_map: '3000'
  version: 1.11.2
  index: /
