name: linuxserver-kasm
services:
  kasm:
    image: linuxserver/kasm:1.19.0@sha256:66b9f3077804154d353b16a65bb78eb8f045b12e836d81930c874d283d0dfd90
    restart: unless-stopped
    environment:
      KASM_PORT: ''
      DOCKER_HUB_USERNAME: ''
      DOCKER_HUB_PASSWORD: ''
      DOCKER_MTU: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/opt
        target: /opt
      - type: bind
        source: /DATA/AppData/$AppID/profiles
        target: /profiles
      - type: bind
        source: /dev/input
        target: /dev/input
      - type: bind
        source: /run/udev/data
        target: /run/udev/data
    container_name: kasm-by-roket
x-casaos:
  main: kasm
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.kasm/assets/icon.png
  title:
    en_US: Kasm
  port_map: '3000'
  id: by-roket.linuxserver.kasm
  version: 1.19.0
  index: /
