name: linuxserver-feed2toot
services:
  feed2toot:
    image: linuxserver/feed2toot:0.17.20250110@sha256:ffb5c6d52ef42c3ac1ca3293ed07d957338df01a48259af9bf355d998de546e2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FEED_LIMIT: ''
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: feed2toot-by-roket
x-casaos:
  main: feed2toot
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.feed2toot/assets/icon.png
  title:
    en_US: Feed2toot
  id: by-roket.linuxserver.feed2toot
  version: 0.17.20250110
  index: /
  port_map: ''
