name: linuxserver-feed2toot
services:
  feed2toot:
    image: linuxserver/feed2toot:0.17.20250110@sha256:bc817b1111908a23fc490c64c10724b0f4ce70cf2621ee6034c2a20986aa8466
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FEED_LIMIT: ''
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: feed2toot-by-roket
x-casaos:
  main: feed2toot
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.feed2toot/assets/icon.png
  title:
    en_US: Feed2toot
  id: by-roket.linuxserver.feed2toot
  version: 0.17.20250110
  index: /
  port_map: ''
