name: linuxserver-dillinger
services:
  dillinger:
    image: linuxserver/dillinger:3.39.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    container_name: dillinger-by-roket
x-casaos:
  main: dillinger
  icon: https://by-roket.github.io/By_Roket-ZimaOS-V2-LinuxServer-Store/apps/by-roket.linuxserver.dillinger/assets/icon.png
  title:
    en_US: Dillinger
  port_map: '8080'
  id: by-roket.linuxserver.dillinger
  version: 3.39.1
  index: /
